### PR TITLE
Fix access list gas

### LINKED ISSUE #272: create_access_list returns incorrect gas consumption
## Summary
#256 implements the Access List functionality, with parts mostly taken from Reth. 
The function works mostly correct, given that the tests of cross-contract calls & wrong storage calls using eth_estimateGas seems feasible.

However, the field of `gas_used` in the `AccessListWithGasUsed` struct returning from `create_access_list` function does not take the access list into account. We should check this.

## Additional Information
https://geth.ethereum.org/docs/interacting-with-geth/rpc/ns-eth#eth-createaccesslist

https://github.com/paradigmxyz/reth/blob/332e412a0f8d34ff2bbb7e07921f8cacdcf69d64/crates/rpc/rpc/src/eth/api/call.rs#L370

https://github.com/chainwayxyz/secret-sovereign-sdk/blob/3551e7ee4c56490afb53d6869c909dab4f1ba655/module-system/module-implementations/sov-evm/src/tests/queries/estimate_gas_tests.rs#L203-L257

### PR DESCRIPTION
**Pull request by otaliptus**
# Description
Closes #272 (finally). Also updated gas estimation from reth. [[1](https://github.com/paradigmxyz/reth/pull/7485)] [[2](https://github.com/paradigmxyz/reth/pull/7521)]

p.s. I still stick with my opinion of better env's though.

### CODE REVIEW

File: crates/evm/src/tests/queries/estimate_gas_tests.rs [hunk 1]
```diff
@@ -218,7 +218,7 @@ fn test_tx_request_fields_gas() {
             .into(),
             // This should actually be 0x6e66
             // See: https://github.com/chainwayxyz/citrea/issues/272
-            gas_used: Uint::from_str("0x6601").unwrap()
+            gas_used: Uint::from_str("0x6e66").unwrap()
```
Comment (eyusufatik) [inline crates/evm/src/tests/queries/estimate_gas_tests.rs:221]: delete todo above

**Review by eyusufatik — CHANGES_REQUESTED** [review]

**Review by eyusufatik — APPROVED** [review]
