### PR TITLE
Disable code flag in post state frame

### LINKED ISSUE #2665: disableCode flag on prestate tracer diffmode does not work
## Summary
It keeps returning code for one of the post/pre states + it always returns the code for unchanged accounts as well, something's off with the filtering there.

### PR DESCRIPTION
**Pull request by rakanalh**
# Description

## Linked Issues
- Fixes #2665

### CODE REVIEW

**Review by eyusufatik — APPROVED** [review]
very good testing!

File: crates/evm/src/rpc_helpers/tracing_utils.rs [hunk 1]
```diff
@@ -108,11 +108,24 @@ pub(crate) fn trace_call<C: sov_modules_api::Context>(
...
                         &mut inspector,
                     )?;
-                    let frame = inspector
+                    let mut frame = inspector
                         .with_transaction_gas_limit(tx_env.gas_limit())
                         .into_geth_builder()
                         .geth_prestate_traces(&res, &prestate_config, &db_ref)
                         .map_err(EthApiError::from_eth_err)?;
+
+                    // Workaround for revm-inspectors v0.18.0 bug where disableCode doesn't filter post state
```
Comment (kpp) [inline crates/evm/src/rpc_helpers/tracing_utils.rs:117]: Upgrade to a new revm will work?

Comment (rakanalh) [reply crates/evm/src/rpc_helpers/tracing_utils.rs:117]: I checked version 0.28 and it doesnt have a fix.
