### PR TITLE
fix: Initialize metrics at startup

### LINKED ISSUE #2952: metrics set to 0 until set for the first time
## Summary
when you restart your full node, until a new proof or commitment is processed, the corresponding metrics for highest committed height and highest proven height are not available. they show up as 0 on our dashboards.

the same goes with the sequencer for the last commitment index, or some of the mmepool metrics.

there should be a systematic way for us to set these values on startup.

### PR DESCRIPTION
**Pull request by rakanalh**
# Description

## Linked Issues
- Fixes #2952

### CODE REVIEW

**Review by jfldde — COMMENTED** [review]
Could we have a single point of initialization instead ? Metrics are already pretty scattered around

**Comment by rakanalh** [comment]
> Could we have a single point of initialization instead ? Metrics are already pretty scattered around

@jfldde What do you mean? We initialize metrics in main and for tests (2 places)

**Comment by jfldde** [comment]
> @jfldde What do you mean? We initialize metrics in main and for tests (2 places)

I used initialize in line with the title PR but I meant setting the previous values. This does it in l1_syncers'/l2_syncers' run methods, commitment service, etc. and clutter the existing methods. We could lift it and centralize it in main maybe ?

**Comment by rakanalh** [comment]
> > @jfldde What do you mean? We initialize metrics in main and for tests (2 places)
> 
> I used initialize in line with the title PR but I meant setting the previous values. This does it in l1_syncers'/l2_syncers' run methods, commitment service, etc. and clutter the existing methods. We could lift it and centralize it in main maybe ?

Could be, but i do believe that having them updated where they should is more appropriate. Since each component manages it's metrics in terms of initialization / update.

**Comment by rakanalh** [comment]
For the record, i had tests written for this. But because of the prometheus exporter being registered globally... it appears having consistently passing tests to be impossible when multiple nodes for multiple tests are running (expecting a clean slate prometheus metrics to be there).

File: bin/citrea/tests/common/client.rs [hunk 1]
```diff
@@ -96,6 +96,12 @@ impl TestClient {
         Ok(resp.status().as_u16())
     }
 
+    pub(crate) async fn get_metrics(&self) -> Result<String, Box<dyn std::error::Error>> {
+        let metrics_url = "http://localhost:9000/metrics".to_owned();
+        let resp = reqwest::get(metrics_url).await?;
+        Ok(resp.text().await?)
+    }
+
     pub(crate) async fn spam_publish_batch_request(
```
Comment (jfldde) [inline bin/citrea/tests/common/client.rs]: Unused

File: bin/citrea/tests/common/helpers.rs [hunk 2]
```diff
@@ -78,6 +80,29 @@ pub async fn start_rollup(
         panic!("Both batch prover and light client prover config cannot be set at the same time");
     }
 
+    if rollup_config.telemetry.bind_host.is_some() && rollup_config.telemetry.bind_port.is_some() {
+        PROMETHEUS_INITIALIZED.get_or_init(|| {
+            let bind_host = rollup_config.telemetry.bind_host.as_ref().unwrap();
+            let bind_port = rollup_config.telemetry.bind_port.unwrap();
```
Comment (jfldde) [inline bin/citrea/tests/common/helpers.rs]: Could use if let Some above instead

File: crates/light-client-prover/src/da_block_handler.rs [hunk 3]
```diff
@@ -82,7 +82,7 @@ impl<Vm, Da, DB> L1BlockHandler<Vm, Da, DB>
 where
     Da: DaService,
     Vm: ZkvmHost + Zkvm,
-    DB: LightClientProverLedgerOps + SharedLedgerOps + Clone,
+    DB: LightClientProverLedgerOps + SharedLedgerOps + Clone + NodeLedgerOps + NodeLedgerOps,
```
Comment (jfldde) [inline crates/light-client-prover/src/da_block_handler.rs]:
```suggestion
    DB: LightClientProverLedgerOps + SharedLedgerOps + Clone + NodeLedgerOps
```

File: crates/light-client-prover/src/da_block_handler.rs [hunk 4]
```diff
@@ -139,6 +139,20 @@ where
...
+            LPM.highest_proven_l2_height
+                .set(proven_height.height as f64);
+            LPM.highest_proven_index
+                .set(proven_height.commitment_index as f64);
+            debug!(
+                "Initialized highest_proven_l2_height metric: {} at index {}",
+                proven_height.height, proven_height.commitment_index
+            );
+        }
+
```
Comment (jfldde) [inline crates/light-client-prover/src/da_block_handler.rs]: Are we sure we're setting the correct value here ?
The fact that we need to add the trait bound `NodeLedgerOps` and use a fullnode method here seems off

File: crates/light-client-prover/src/da_block_handler.rs [hunk 5]
```diff
@@ -139,6 +139,20 @@ where
         last_l1_height_scanned: StartVariant,
         mut shutdown_signal: GracefulShutdown,
     ) {
+        if let Ok(Some(proven_height)) = self
+            .ledger_db
+            .get_highest_l2_height_for_status(sov_db::schema::types::L2HeightStatus::Proven, None)
```
Comment (jfldde) [inline crates/light-client-prover/src/da_block_handler.rs]: Table is not accessible to lcp. We should propagate the error instead of silently skipping the Err imo.

File: bin/citrea/tests/common/helpers.rs (hunk 2 above)
Comment (rakanalh) [reply bin/citrea/tests/common/helpers.rs]: I did this, but since we cannot chain if let some, i am reverting this.

**Review by jfldde — DISMISSED** [review]

File: crates/light-client-prover/src/metrics.rs [hunk 6]
```diff
@@ -51,3 +51,45 @@ pub static LIGHT_CLIENT_METRICS: LazyLock<LightClientProverMetrics> = LazyLock::
...
+/// Initializes light client prover metrics with current DB state
+///
+/// # Arguments
+/// * `ledger_db` - The ledgerDB to read metrics from
+///
+/// # Errors
+/// Returns error if database operations fail
+pub fn initialize_metrics<DB>(ledger_db: &DB) -> Result<(), anyhow::Error>
+where
+    DB: sov_db::ledger_db::LightClientProverLedgerOps + sov_db::ledger_db::SharedLedgerOps,
```
Comment (jfldde) [inline crates/light-client-prover/src/metrics.rs]:
```suggestion
    DB: sov_db::ledger_db::LightClientProverLedgerOps,
```

File: crates/light-client-prover/src/services.rs [hunk 7]
```diff
@@ -59,13 +59,18 @@ pub fn build_services<Vm, Da, DB>(
 where
     Da: DaService,
     Vm: ZkvmHost + Zkvm,
-    DB: LightClientProverLedgerOps + SharedLedgerOps + Clone + 'static,
+    DB: LightClientProverLedgerOps + SharedLedgerOps + NodeLedgerOps + Clone + 'static,
```
Comment (jfldde) [inline crates/light-client-prover/src/services.rs]:
```suggestion
    DB: LightClientProverLedgerOps + Clone + 'static,
```

File: crates/sequencer/src/metrics.rs [hunk 8]
```diff
@@ -174,3 +174,42 @@ pub static RETH_BLOB_STORE_METRICS: LazyLock<BlobStoreMetrics> = LazyLock::new(|
...
+/// Initializes sequencer metrics with current DB state
+///
+/// # Arguments
+/// * `ledger_db` - The ledgerDB to read metrics from
+///
+/// # Errors
+/// Returns error if database operations fail
+pub fn initialize_metrics<DB>(ledger_db: &DB) -> Result<(), anyhow::Error>
+where
+    DB: sov_db::ledger_db::SequencerLedgerOps + sov_db::ledger_db::SharedLedgerOps,
```
Comment (jfldde) [inline crates/sequencer/src/metrics.rs]:
```suggestion
    DB: sov_db::ledger_db::SequencerLedgerOps,
```

File: crates/light-client-prover/src/services.rs [hunk 9]
```diff
@@ -7,7 +7,7 @@ use citrea_common::backup::BackupManager;
 use citrea_common::LightClientProverConfig;
 use jsonrpsee::RpcModule;
 use prover_services::ParallelProverService;
-use sov_db::ledger_db::{LightClientProverLedgerOps, SharedLedgerOps};
+use sov_db::ledger_db::{LightClientProverLedgerOps, NodeLedgerOps, SharedLedgerOps};
```
Comment (jfldde) [inline crates/light-client-prover/src/services.rs]:
```suggestion
use sov_db::ledger_db::LightClientProverLedgerOps;
```

**Review by jfldde — DISMISSED** [review]
LGTM but for a few nits

**Review by jfldde — DISMISSED** [review]

File: bin/citrea/tests/common/helpers.rs [hunk 10]
```diff
@@ -78,6 +80,29 @@ pub async fn start_rollup(
         panic!("Both batch prover and light client prover config cannot be set at the same time");
     }
 
+    if rollup_config.telemetry.bind_host.is_some() && rollup_config.telemetry.bind_port.is_some() {
```
Comment (kpp) [inline bin/citrea/tests/common/helpers.rs:83]: Why not if let Some as you did in one of commits?

**Review by kpp — COMMENTED** [review]
LGTM. The only thing that bothers me is inconsistent calls to `initialize_metrics` in different places like in lib.rs or services.rs or runner.rs.

**Comment by rakanalh** [comment]
They're all called in `build_services`... except for the sequencer. I could adjust

**Review by jfldde — DISMISSED** [review]

File: CHANGELOG.md [hunk 11]
```diff
@@ -20,6 +20,7 @@
 - ci: Run citrea-e2e tests against bitcoin v30 ([#3054](https://github.com/chainwayxyz/citrea/pull/3054))
 - feat: Add `citrea-cli db-migrate` subcommand ([#3015](https://github.com/chainwayxyz/citrea/pull/3015))\
   Usage: `citrea-cli db-migrate --node-type <NODE_TYPE> --db-path <DB_PATH>`
+- fix: Initialize metrics at startup. ([#2954](https://github.com/chainwayxyz/citrea/pull/2954))
```
Comment (eyusufatik) [inline CHANGELOG.md]: I think this went to the wrong place

File: CHANGELOG.md [hunk 12]
```diff
@@ -171,8 +172,14 @@ For a detailed list of changes, see auto generated changelog at [v0.6.0 release
...
+[unreleased]: https://github.com/chainwayxyz/citrea/compare/release-v0.8.1...HEAD
+||||||| 8c77d6e1f
+[unreleased]: https://github.com/chainwayxyz/citrea/compare/release-v0.8.1...HEAD
+=======
 [unreleased]: https://github.com/chainwayxyz/citrea/compare/v1.1.0...HEAD
 [v1.1.0]: https://github.com/chainwayxyz/citrea/compare/v1.0.2...v1.1.0
 [v1.0.2]: https://github.com/chainwayxyz/citrea/compare/v1.0.1...v1.0.2
 [v1.0.1]: https://github.com/chainwayxyz/citrea/compare/v1.0.0...v1.0.1
 [v1.0.0]: https://github.com/chainwayxyz/citrea/compare/v0.9.0...v1.0.0
+>>>>>>> origin/nightly
```
Comment (eyusufatik) [inline CHANGELOG.md]: also you forgot this part

File: crates/sequencer/src/metrics.rs [hunk 13]
```diff
@@ -174,3 +174,42 @@ pub static RETH_BLOB_STORE_METRICS: LazyLock<BlobStoreMetrics> = LazyLock::new(|
...
+    if let Ok(Some(commitment)) = ledger_db.get_last_commitment() {
+        SEQUENCER_METRICS
+            .latest_sequencer_commitment_index
+            .set(commitment.index as f64);
+        SEQUENCER_METRICS
+            .latest_sequencer_commitment_l2_end_height
+            .set(commitment.l2_end_block_number as f64);
+        SEQUENCER_METRICS
+            .currently_committing_index
+            .set(commitment.index as f64);
```
Comment (eyusufatik) [inline crates/sequencer/src/metrics.rs]: let's not set this one in order not to confuse anybody if we put this in a dashboard

File: crates/light-client-prover/src/services.rs [hunk 14]
```diff
@@ -59,13 +59,18 @@ pub fn build_services<Vm, Da, DB>(
 where
     Da: DaService,
     Vm: ZkvmHost + Zkvm,
-    DB: LightClientProverLedgerOps + SharedLedgerOps + Clone + 'static,
+    DB: LightClientProverLedgerOps + Clone + 'static,
```
Comment (eyusufatik) [inline crates/light-client-prover/src/services.rs:62]: why the change here?

File: crates/batch-prover/src/metrics.rs [hunk 15]
```diff
@@ -65,3 +65,39 @@ pub static BATCH_PROVER_METRICS: LazyLock<BatchProverMetrics> = LazyLock::new(||
...
 });
+
+/// Initializes batch prover metrics with current DB state
+///
+/// # Arguments
+/// * `ledger_db` - The ledgerDB to read metrics from
+///
+/// # Errors
+/// Returns error if database operations fail
+pub fn initialize_metrics<DB>(ledger_db: &DB) -> Result<(), anyhow::Error>
```
Comment (eyusufatik) [inline crates/batch-prover/src/metrics.rs:77]: pls also set ongoing proving jobs to 0 if that's possible

**Review by eyusufatik — CHANGES_REQUESTED** [review]

File: crates/light-client-prover/src/services.rs (hunk 14 above)
Comment (rakanalh) [reply crates/light-client-prover/src/services.rs:62]: A cleaned up that @jfldde suggested.

File: crates/batch-prover/src/metrics.rs (hunk 15 above)
Comment (rakanalh) [reply crates/batch-prover/src/metrics.rs:77]: Done

File: crates/light-client-prover/src/services.rs (hunk 14 above)
Comment (jfldde) [reply crates/light-client-prover/src/services.rs:62]: trait is declared as `pub trait LightClientProverLedgerOps: SharedLedgerOps + Send + Sync`, so `+ SharedLedgerOps` was redundant

**Review by eyusufatik — APPROVED** [review]

**Review by jfldde — APPROVED** [review]
