### PR TITLE
fix: Limit available RPC methods per node type

### LINKED ISSUE #3086: Light client prover has all RPCs
## Summary
We register all STF RPCs to the light client prover, even though it's not doing any STF related operations.

See:
```sh
curl --location 'https://light-client-prover.mainnet.citrea.xyz' \
--header 'Content-Type: application/json' \
--data '{
    "jsonrpc": "2.0",
    "id": 1,
    "method": "eth_blockNumber",
    "params": []
}'
```

## Expected Result

```json
{
    "jsonrpc": "2.0",
    "id": 1,
    "error": {
        "code": -32601,
        "message": "Method not found"
    }
}
```

## Actual Result

```json
{
    "jsonrpc": "2.0",
    "id": 1,
    "result": "0x0"
}
```

## Additional Information

This happens because we do below for all node types:

```rust
fn create_rpc_methods(
      &self,
      storage: ProverStorage,
      ledger_db: &LedgerDB,
      da_service: &Arc<Self::DaService>,
      backup_manager: &Arc<BackupManager>,
      rpc_config: RpcConfig,
  ) -> Result<jsonrpsee::RpcModule<()>, anyhow::Error> {
      // unused inside register RPC
      let sov_sequencer = Address::new([0; 32]);

      let mut rpc_methods = sov_modules_rollup_blueprint::register_rpc::<
          Self::DaService,
          CitreaRuntime<DefaultContext, Self::DaSpec>,
      >(storage.clone(), ledger_db, sov_sequencer, rpc_config)?;

      let backup_methods = create_backup_rpc_module(ledger_db.clone(), backup_manager.clone());
      rpc_methods.merge(backup_methods)?;

      let da_methods = create_da_rpc_module(da_service.clone());
      rpc_methods.merge(da_methods)?;

      Ok(rpc_methods)
  }
```

We must not include runtime RPCs in the light client prover, because this happens in the logs:

```sh
thread 'tokio-runtime-worker' panicked at 'EVM config must be set at genesis': /home/runner/work/citrea/citrea/crates/evm/src/query.rs:127
   0: <backtrace::capture::Backtrace as core::default::Default>::default
   1: log_panics::Config::install_panic_hook::{{closure}}
   2: std::panicking::rust_panic_with_hook
   3: std::panicking::begin_panic_handler::{{closure}}
   4: std::sys::backtrace::__rust_end_short_backtrace
   5: __rustc::rust_begin_unwind
   6: core::panicking::panic_fmt
   7: core::option::expect_failed
   8: jsonrpsee_core::server::rpc_module::RpcModule<Context>::register_method::{{closure}}
   9: <citrea_common::rpc::metrics::RpcMetrics<S> as jsonrpsee_server::middleware::rpc::RpcServiceT>::call::{{closure}}
  10: <citrea_common::rpc::Logger<S> as jsonrpsee_server::middleware::rpc::RpcServiceT>::call::{{closure}}
  11: <core::pin::Pin<P> as core::future::future::Future>::poll
  12: jsonrpsee_server::server::handle_rpc_call::{{closure}}
  13: <jsonrpsee_server::server::TowerServiceNoHttp<RpcMiddleware> as tower_service::Service<http::request::Request<Body>>>::call::{{closure}}
  14: <jsonrpsee_server::middleware::http::proxy_get_request::ProxyGetRequest<S> as tower_service::Service<http::request::Request<B>>>::call::{{closure}}
  15: <jsonrpsee_server::utils::TowerToHyperServiceFuture<S,R> as core::future::future::Future>::poll
  16: hyper::proto::h1::dispatch::Dispatcher<D,Bs,I,T>::poll_loop
  17: <core::pin::Pin<P> as core::future::future::Future>::poll
  18: jsonrpsee_server::server::process_connection::{{closure}}
  19: tokio::runtime::task::raw::poll
  20: tokio::runtime::scheduler::multi_thread::worker::Context::run_task
  21: tokio::runtime::scheduler::multi_thread::worker::run
  22: tokio::runtime::task::raw::poll
  23: std::sys::backtrace::__rust_begin_short_backtrace
  24: core::ops::function::FnOnce::call_once{{vtable.shim}}
  25: std::sys::pal::unix::thread::Thread::new::thread_start
  26: <unknown>
  27: __clone
```

which happens because LCP never actually runs the genesis set up for the L2. Thus it shouldn't try to answer for runtime RPCs like evm's or l2 block rule enforcer's etc.

### PR DESCRIPTION
**Pull request by jfldde**
# Description

- Restrict runtime RPC methods to non-lcp nodes and da RPC methods to sequencer and batch-prover

## Linked Issues
- Fixes #3086

### CODE REVIEW

File: bin/citrea/src/rollup/mock.rs [hunk 1]
```diff
@@ -45,19 +46,23 @@ impl RollupBlueprint for MockDemoRollup {
...
+        // runtime rpc.
+        let mut rpc_methods =
+            <CitreaRuntime<DefaultContext, Self::DaSpec>>::rpc_methods(storage, ledger_db.clone());
+
+        // ledger rpc.
+        let ledger_db_methods = sov_ledger_rpc::server::create_rpc_module::<LedgerDB>(
+            ledger_db.clone(),
+            rpc_config.into(),
+        );
+        rpc_methods.merge(ledger_db_methods)?;
```
Comment (eyusufatik) [inline bin/citrea/src/rollup/mock.rs:66]: should we do the same with bitcoin.rs here? maybe it can be differnet idk. what's your reasoning?

**Review by eyusufatik — DISMISSED** [review]

**Review by eyusufatik — DISMISSED** [review]

File: bin/citrea/src/rollup/bitcoin.rs [hunk 2]
```diff
@@ -65,25 +67,39 @@ impl RollupBlueprint for BitcoinRollup {
...
     fn create_rpc_methods(
         &self,
+        node_type: NodeType,
         storage: ProverStorage,
         ledger_db: &LedgerDB,
         da_service: &Arc<Self::DaService>,
         backup_manager: &Arc<BackupManager>,
         rpc_config: RpcConfig,
     ) -> Result<jsonrpsee::RpcModule<()>, anyhow::Error> {
         // unused inside register RPC
```
Comment (exeokan) [inline bin/citrea/src/rollup/bitcoin.rs]: > // unused inside register RPC

I think this comment was referring to the removed variable `sov_sequencer`

**Review by exeokan — CHANGES_REQUESTED** [review]

**Review by exeokan — APPROVED** [review]

**Review by kpp — APPROVED** [review]

**Review by eyusufatik — APPROVED** [review]
