### PR TITLE
guest side proof fail

### LINKED ISSUE #1643: Guest verify should not panic
## Steps to reproduce

1.
2.

### PR DESCRIPTION
**Pull request by eyusufatik**
# Description
since risc0 guest side proof verification APIs only support proofs that are verifiable, we need to verify failing of proofs with host side verification API.

TODO:
- [x] figure out how to test this in e2e

## Linked Issues
Fixes #1643

### CODE REVIEW

File: crates/light-client-prover/src/circuit.rs [hunk 1]
```diff
@@ -161,8 +167,19 @@ pub fn run_circuit<DaV: DaVerifier, G: ZkvmGuest>(
...
+                        {
+                            // if index is not in the expected to fail hints, then it should pass
+                            G::verify(&journal, &batch_proof_method_id.into())
+                                .expect("Proof hinted to pass failed");
+                        } else {
+                            // if index is in the expected to fail hints, then it should fail
+                            G::verify_expected_to_fail(&proof, &batch_proof_method_id.into())
+                                .expect_err("Proof hinted to fail passed");
+                            expected_to_fail_hints.next();
+                            current_proof_index += 1;
```
Comment (jfldde) [inline crates/light-client-prover/src/circuit.rs]:
```suggestion
if expected_to_fail_hints.next_if(|&x| x == current_proof_index).is_none() {
    // if index is not in the expected to fail hints, then it should pass
    G::verify(&journal, &batch_proof_method_id.into())
        .expect("Proof hinted to pass failed");
} else {
    // if index is in the expected to fail hints, then it should fail
    G::verify_expected_to_fail(&proof, &batch_proof_method_id.into())
        .expect_err("Proof hinted to fail passed");
    current_proof_index += 1;
    continue;
}
```
Can use `next_if` so we don't need to unwrap to u32::MAX.

**Review by jfldde — APPROVED** [review]
LGTM but for the small nit above

File: crates/light-client-prover/src/circuit.rs [hunk 2]
```diff
@@ -174,24 +174,21 @@ pub fn run_circuit<DaV: DaVerifier, G: ZkvmGuest>(
                             // if index is not in the expected to fail hints, then it should pass
                             G::verify(&journal, &batch_proof_method_id.into())
                                 .expect("Proof hinted to pass failed");
+                            recursive_match_state_roots(
```
Comment (eyusufatik) [inline crates/light-client-prover/src/circuit.rs:178]: nooo dont move this

Comment (yaziciahmet) [reply crates/light-client-prover/src/circuit.rs:178]: why ser? isn't it the same thing? changed this as it seemed easier to track the flow this way.

File: crates/light-client-prover/src/circuit.rs (hunk 1 above)
Comment (yaziciahmet) [reply crates/light-client-prover/src/circuit.rs]: https://github.com/chainwayxyz/citrea/pull/1653/commits/14d2b3ea3a2c074d4962d7c665ed92769dad372b

**Comment by eyusufatik** [comment]
https://github.com/chainwayxyz/citrea/pull/1647#discussion_r1901259530

DO BEFORE MERGING ^

File: bin/citrea/tests/bitcoin_e2e/light_client_test.rs [hunk 3]
```diff
@@ -726,3 +729,197 @@ async fn test_light_client_batch_proof_method_id_update() -> Result<()> {
...
+            final_state_root: [1u8; 32],
+            last_l2_height: 1000,
+            da_slot_hash: [0u8; 32].into(),
+            prev_soft_confirmation_hash: [0u8; 32],
+            final_soft_confirmation_hash: [0u8; 32],
+            state_diff: BTreeMap::new(),
+            sequencer_commitments_range: (0, 0),
+            sequencer_da_public_key: [0u8; 32].to_vec(),
+            sequencer_public_key: [0u8; 32].to_vec(),
+            preproven_commitments: vec![],
```
Comment (eyusufatik) [inline bin/citrea/tests/bitcoin_e2e/light_client_test.rs]: you'll need to provide proofs with this order

verifiable 1 
unverifiable 
verifiable 3 
verifiable 2 

and you'll assert light client proof output.state root == 3.state root

File: crates/light-client-prover/src/circuit.rs [hunk 4]
```diff
@@ -147,6 +153,7 @@ pub fn run_circuit<DaV: DaVerifier, G: ZkvmGuest>(
                                 batch_proof_method_ids[0].1
                             } else {
                                 // If not continue to the next blob
+                                current_proof_index += 1;
```
Comment (eyusufatik) [inline crates/light-client-prover/src/circuit.rs]: maybe remove?

Comment (eyusufatik) [reply crates/light-client-prover/src/circuit.rs]: let's remove this if else altogether and return batch_proof_method_ids[0].1

**Review by kpp — APPROVED** [review]
