### PR TITLE
fix: Take queried hashes removes elements for better memory management

### LINKED ISSUE #2706: `NativeShortHeaderProofProviderService:: take_queried_hashes` can remove taken hashes
## Summary
Better memory management

### PR DESCRIPTION
**Pull request by ercecan**
# Description

## Linked Issues
- Fixes #2706

### CODE REVIEW

**Review by jfldde — APPROVED** [review]

File: crates/short-header-proof-provider/src/native.rs [hunk 1]
```diff
@@ -99,16 +99,18 @@ impl<Da: DaSpec> ShortHeaderProofProvider for NativeShortHeaderProofProviderServ
...
+
         for l2_height in l2_range {
-            if let Some(queried_hashes) = queried_and_verified_hashes.get(&l2_height) {
-                hashes.try_reserve(queried_hashes.len()).map_err(|e| {
+            if let Some(mut taken) = map.remove(&l2_height) {
+                hashes.try_reserve(taken.len()).map_err(|e| {
                     ShortHeaderProofProviderError::VectorAllocationFailed(e.to_string())
                 })?;
-                hashes.extend(queried_hashes.clone());
+                hashes.append(&mut taken);
```
Comment (jfldde) [inline crates/short-header-proof-provider/src/native.rs]: We could extend without mut instead as it's not a hotpath (native)

**Review by eyusufatik — APPROVED** [review]
