### PR TITLE
witnessed light client proof

### LINKED ISSUE #1807: Bonsai only supports succinct assumption receipts
## Summary

`2025-02-04T13:59:23.867364Z ERROR panic: thread '<unnamed>' panicked at 'Proof creation must not fail: Bonsai only supports succinct assumption receipts. Use `ProverOpts::succinct()` when proving any assumptions.': /home/kpp/chainway/secret-sovereign-sdk/crates/prover-services/src/parallel/mod.rs:166
`

## Steps to reproduce

Run `test_light_client_proving_multiple_proofs` with bonsai api key set.

## Expected Result

Test passes

## Actual Result

Error

## Additional Information

With this patch it works 

```diff
index 36a31a2b..d4296e86 100644
--- a/crates/risc0/src/host.rs
+++ b/crates/risc0/src/host.rs
@@ -165,7 +165,7 @@ impl ZkvmHost for Risc0BonsaiHost {
         tracing::info!("Starting risc0 proving");
 
         let ProveInfo { receipt, stats } =
-            prover.prove_with_opts(env, &elf, &ProverOpts::groth16())?;
+            prover.prove_with_opts(env, &elf, &ProverOpts::succinct())?;
 
```

### LINKED ISSUE #1814: Recursive SNARK verification problems
Apparently if you verify a Groth16 proof in-circuit with the risc0 env API, you can only produce a composite receipt. 

We might need to switch to host side verification, just like we did with the proofs that should fail.

### LINKED ISSUE #1945: Light client verifies L1 hash from batch proof output
Should be done after #1771 and #1986

The Fork2 batch proof always outputs the highest L1 hash on its Bitocin Light Cleint contract.

We'll verify the batch proof's outputted hash belongs to our JMT of blockhashes. If a batch proof outputs an L1 hash that does not belong to our JMT, we discard that batch proof.

### LINKED ISSUE #1986: Light client circuit builds JMT of L1 block hashes
Since we need to verify if a batch proof's last_l1_hash output exists in the header chain (or does not exist so we can ignore the proof), we need a merklized structure that has inclusion and exclusion proofs.

On our benchmarks we've found a JMT with keyhashes as Bitcoin blockhashes and values as empty vec's perform on par with regular merkle trees.

So we'll be creating a JMT of blockhashes starting from the first L1 block the light client proof processes.

### LINKED ISSUE #2018: Push proof chunks to JMT
Let's push chunks to the LCP JMT.

key = "c" + chunk.wtxid
value = chunk.body

### PR DESCRIPTION
**Pull request by eyusufatik**
# Description
Shares light client proof circuit logic between native and zk enabling us to use the same methods of input creation for the batch proof circuit.

This will make it really easy to implement linked issues, which I'll be doing in this PR.

## Linked Issues
Closes #2018 
Closes #1986 
Closes #1945

This one makes my job easier to finish this pr:
Closes #1814 
Closes #1807

TODOs:

- [x] Write tests for accessors
- [x] Move old circuit logic into new circuit
- [x] Remove MMRDb and everything related
- [x] Update input output types for light client proof
- [x] Finish #1814 and remove expected to fail hints
- [x] check if x network elf changes on your network constant change (testing https://github.com/chainwayxyz/citrea/pull/2028/commits/723618fd745dd675e4b72b38d9303ea20a97209f)
- [x] Reintroduce assumptions (deleted in this branch) only to verify previous lcp
- [x] #1945 
- [x] Write native side circuit & hint usage
- [x] Fix tests
- [x] Write unknown L1 blockhash batch proof no verification test
- [x] remove da_data from light client proof circuit input

### CODE REVIEW

File: crates/light-client-prover/src/circuit/accessors.rs [hunk 1]
```diff
@@ -0,0 +1,185 @@
...
+/// don't want the serialization overhead.
+use sov_modules_api::{StateReaderAndWriter, WorkingSet};
+use sov_modules_core::{Prefix, Storage, StorageKey, StorageValue};
+
+pub struct BlockHashAccessor<S: Storage> {
+    phantom: core::marker::PhantomData<S>,
+}
+
+impl<S: Storage> BlockHashAccessor<S> {
+    const PREFIX: u8 = 98u8; // lowercase b
```
Comment (jfldde) [inline crates/light-client-prover/src/circuit/accessors.rs]:
```suggestion
    const PREFIX: u8 = b'b';
```

File: crates/light-client-prover/src/circuit/accessors.rs [hunk 2]
```diff
@@ -0,0 +1,185 @@
...
+/// We don't use the StateMap or Module system here, as our keys are all hashes of different things, we
+/// don't want the serialization overhead.
+use sov_modules_api::{StateReaderAndWriter, WorkingSet};
+use sov_modules_core::{Prefix, Storage, StorageKey, StorageValue};
+
+pub struct BlockHashAccessor<S: Storage> {
+    phantom: core::marker::PhantomData<S>,
+}
+
+impl<S: Storage> BlockHashAccessor<S> {
```
Comment (jfldde) [inline crates/light-client-prover/src/circuit/accessors.rs:12]:
```
pub trait StorageAccessor<S: Storage> {
    const PREFIX: u8;
    fn get(id: [u8; 32], working_set: &mut WorkingSet<S>) -> Option<Vec<u8>>;
    fn insert(id: [u8; 32], value: Vec<u8>, working_set: &mut WorkingSet<S>);

    fn contains(id: [u8; 32], working_set: &mut WorkingSet<S>) -> bool {
        Self::get(id, working_set).is_some()
    }
}
```
Would make it cleaner and has the benefits of default contains impl

Comment (eyusufatik) [reply crates/light-client-prover/src/circuit/accessors.rs:12]: I am not yet sure if all accessors will be returning the same type. (I think they wont) And I don't want to have the trait have a bunch of Key and Value generics and make it all too much abstracted sov-storage code again :D

but once I'm finished I'll come back and reconsider this comment.

File: crates/light-client-prover/src/circuit/accessors.rs [hunk 3]
```diff
@@ -0,0 +1,185 @@
...
+    const PREFIX: u8 = 98u8; // lowercase b
+
+    pub fn exists(hash: [u8; 32], working_set: &mut WorkingSet<S>) -> bool {
+        // use `StateKey::singleton` as a hack to create no serialization key
+        let mut key = [0u8; 33]; // 1 prefix + 32 hash
+
+        key[0..1].copy_from_slice(&[Self::PREFIX]);
```
Comment (yaziciahmet) [inline crates/light-client-prover/src/circuit/accessors.rs]: key[0] = Self::PREFIX;

do everywhere in this file

File: crates/sovereign-sdk/rollup-interface/src/state_machine/da.rs [hunk 4]
```diff
@@ -165,6 +165,9 @@ pub trait DaSpec:
         + BorshSerialize
         + Send
         + Sync;
+
+    /// Decompress chunks to complete
+    fn decompress_chunks(complete_chunks: &[u8]) -> Result<Vec<u8>, ()>;
```
Comment (yaziciahmet) [inline crates/sovereign-sdk/rollup-interface/src/state_machine/da.rs]: I don't like this here :/

File: crates/light-client-prover/src/da_block_handler.rs [hunk 5]
```diff
@@ -162,169 +172,54 @@ where
...
+                (None, 0, None)
             }
         };
 
-        let batch_proofs = self.extract_batch_proofs(&mut da_data, l1_hash).await;
-        tracing::info!(
-            "Block {} has {} batch proofs",
-            l1_height,
-            batch_proofs.len()
+        let storage = self.storage_manager.create_storage_for_next_l2_height();
```
Comment (yaziciahmet) [inline crates/light-client-prover/src/da_block_handler.rs:197]: I don't understand this

**Review by yaziciahmet — CHANGES_REQUESTED** [review]
Great job overall, will re-review once the PR is complete

File: crates/light-client-prover/src/da_block_handler.rs (hunk 5 above)
Comment (yaziciahmet) [reply crates/light-client-prover/src/da_block_handler.rs:197]: because are we sure that whatever is the latest l2 height for the light client proof is within the currently being proven l1 block?

Comment (eyusufatik) [reply crates/light-client-prover/src/da_block_handler.rs:197]: I am kinda hacking our storage api with that one. That height is  just an incremental number 🤷‍♂️

File: crates/light-client-prover/src/circuit/accessors.rs (hunk 2 above)
Comment (eyusufatik) [reply crates/light-client-prover/src/circuit/accessors.rs:12]: wont be doing this

File: crates/common/src/backup/manager.rs [hunk 6]
```diff
@@ -23,16 +22,16 @@ pub struct BackupConfig {
...
+        let backup_dirs = vec![
             LEDGER_DB_PATH_SUFFIX.to_string(),
             StateDB::DB_PATH_SUFFIX.to_string(),
             NativeDB::DB_PATH_SUFFIX.to_string(),
         ];
 
-        if node_kind == "light-client-prover" {
-            backup_dirs.push(MmrDB::DB_PATH_SUFFIX.to_string());
-        }
+        // if node_kind == "light-client-prover" {
```
Comment (eyusufatik) [inline crates/common/src/backup/manager.rs]: remove

File: crates/common/src/backup/mod.rs [hunk 7]
```diff
@@ -38,6 +38,8 @@
 //! ├── state/        # Required - stores state database
 //! ├── native-db/    # Required - stores native database
 //! └── mmr/          # Optional - used by light client prover
+//!
```
Comment (eyusufatik) [inline crates/common/src/backup/mod.rs]: just remove and update comments

File: crates/light-client-prover/src/da_block_handler.rs [hunk 8]
```diff
@@ -41,54 +44,61 @@ where
...
 {
+    network: Network,
     _prover_config: LightClientProverConfig,
     prover_service: Arc<ParallelProverService<Da, Vm>>,
+    storage_manager: ProverStorageManager,
     ledger_db: DB,
     da_service: Arc<Da>,
-    batch_prover_da_pub_key: Vec<u8>,
-    batch_proof_code_commitments: HashMap<SpecId, Vm::CodeCommitment>,
+    // TODO: maybe remove these
```
Comment (eyusufatik) [inline crates/light-client-prover/src/da_block_handler.rs]: remove

File: crates/light-client-prover/src/da_block_handler.rs [hunk 9]
```diff
@@ -384,7 +290,7 @@ where
     /// - Ok(true) -> proof is successfully parsed, not a duplicate, and verified
     /// - Ok(false) -> proof is successfully parsed, not a duplicate, but verification failed
     /// - Err(_) -> proof is either unparseable or a duplicate
-    fn verify_complete_proof(
+    fn _verify_complete_proof(
```
Comment (eyusufatik) [inline crates/light-client-prover/src/da_block_handler.rs]: remove

File: crates/light-client-prover/src/da_block_handler.rs [hunk 10]
```diff
@@ -430,7 +336,7 @@ where
         }
     }
 
-    async fn extract_batch_proofs(
+    async fn _extract_batch_proofs(
```
Comment (eyusufatik) [inline crates/light-client-prover/src/da_block_handler.rs]: remove

File: crates/light-client-prover/src/circuit/accessors.rs [hunk 11]
```diff
@@ -0,0 +1,185 @@
...
+        let (read_write_log, mut witness) = working_set.checkpoint().freeze();
+
+        // assert_eq!(witness.len(), 2);
+
+        let (_, state_update, _) = prover_storage
+            .compute_state_update(&read_write_log, &mut witness)
+            .expect("should not fail");
+
+        // sanity check
+        // why 6?
```
Comment (eyusufatik) [inline crates/light-client-prover/src/circuit/accessors.rs]: why 5?

File: crates/light-client-prover/src/circuit/accessors.rs [hunk 12]
```diff
@@ -0,0 +1,185 @@
...
+        assert_eq!(
+            ChunkAccessor::<ProverStorage>::get([1; 32], &mut working_set).unwrap(),
+            vec![12; 150]
+        );
+
+        assert!(ChunkAccessor::<ProverStorage>::get([2; 32], &mut working_set).is_none());
+
+        let (read_write_log, mut witness) = working_set.checkpoint().freeze();
+
+        // assert_eq!(witness.len(), 2);
```
Comment (eyusufatik) [inline crates/light-client-prover/src/circuit/accessors.rs]: remove

File: crates/light-client-prover/src/circuit/mod.rs [hunk 13]
```diff
@@ -0,0 +1,449 @@
...
+                                continue;
+                            }
+                        }
+                    }
+
+                    println!("Aggregate has all needed chunks!");
+
+                    let complete_proof: Vec<_> = chunks.into_iter().flatten().collect();
+
+                    // TODO: figure out how to do this.
```
Comment (eyusufatik) [inline crates/light-client-prover/src/circuit/mod.rs]: remove todo

File: crates/light-client-prover/src/circuit/mod.rs [hunk 14]
```diff
@@ -0,0 +1,449 @@
...
+
+                    match self.process_complete_proof(
+                        &complete_proof,
+                        &batch_proof_method_ids,
+                        last_l2_height,
+                        &mut initial_to_final,
+                        &mut working_set,
+                    ) {
+                        Ok(()) => {}
+                        // serialization or duplicate proof error
```
Comment (eyusufatik) [inline crates/light-client-prover/src/circuit/mod.rs]: comment is misleading. can be unverified error as well

File: crates/light-client-prover/src/circuit/mod.rs [hunk 15]
```diff
@@ -0,0 +1,449 @@
...
+            last_l2_height = last_l2;
+            last_l2_state_root = final_root;
+        }
+
+        // Collect unchained outputs
+        let unchained_outputs = collect_unchained_outputs(&initial_to_final, last_l2_height);
+
+        let (read_write_log, mut witness) = working_set.checkpoint().freeze();
+
+        // TODO: compute_state_update cretes state diff
```
Comment (eyusufatik) [inline crates/light-client-prover/src/circuit/mod.rs]: create issue for this

File: crates/light-client-prover/src/circuit/mod.rs [hunk 16]
```diff
@@ -0,0 +1,449 @@
...
+        // which we don't need in this circuit
+        // maybe create new function or pass argument for state diff building
+        let (lcp_state_root_transition, jmt_state_update, _) = storage
+            .compute_state_update(&read_write_log, &mut witness)
+            .expect("jellyfish merkle tree update must succeed");
+
+        if let Some(output) = previous_light_client_proof_output {
```
Comment (eyusufatik) [inline crates/light-client-prover/src/circuit/mod.rs:333]: add comment here explaining why we do this

File: crates/light-client-prover/src/circuit/mod.rs [hunk 17]
```diff
@@ -0,0 +1,449 @@
...
+                lcp_state_root_transition.init_root,
+                const_hex::decode_to_array(
+                    "5350415253455f4d45524b4c455f504c414345484f4c4445525f484153485f5f"
+                )
+                .unwrap()
+            );
+        }
+
+        // TODO: assert initial root here
+        // TODO: also if prev out is none, the prev root must be some specific root.
```
Comment (eyusufatik) [inline crates/light-client-prover/src/circuit/mod.rs]: remove todo

File: crates/light-client-prover/src/tests/mod.rs [hunk 18]
```diff
@@ -794,627 +894,45 @@ fn test_missing_chunk() {
...
-        ([1; 32], chunk1.clone()),
-        ([2; 32], chunk2.clone()),
-        ([3; 32], chunk3.clone()),
-    ];
-
-    let mut mmr_hints = create_mmr_hints(&mut mmr_guest, chunks);
-
-    // Malform the inclusion proof
-    mmr_hints[0].1.inclusion_proof.push(MMRNodeHash::default());
-
```
Comment (eyusufatik) [inline crates/light-client-prover/src/tests/mod.rs:1376]: as mmr fiddling tests are removed, we should implement jmt hints fiddling tests. open issue for this

File: bin/citrea/tests/bitcoin/bitcoin_test.rs [hunk 19]
```diff
@@ -104,7 +104,7 @@ impl TestCase for BitcoinReorgTest {
         assert!(matches!(tx_status, Some(TxStatus::Pending { .. })));
 
         // Wait for re-org monitoring
-        tokio::time::sleep(Duration::from_secs(5)).await;
+        tokio::time::sleep(Duration::from_secs(20)).await;
```
Comment (rakanalh) [inline bin/citrea/tests/bitcoin/bitcoin_test.rs:107]: 20 seconds is a lot of wait... can we document why this is?

File: bin/citrea/src/main.rs [hunk 20]
```diff
@@ -106,6 +107,7 @@ where
     DaC: serde::de::DeserializeOwned + DebugTrait + Clone + FromEnv + Send + Sync + 'static,
     S: CitreaRollupBlueprint<DaConfig = DaC>,
     <DefaultContext as Spec>::Storage: NativeStorage,
+    Network: InitialValueProvider<<S as RollupBlueprint>::DaSpec>,
```
Comment (rakanalh) [inline bin/citrea/src/main.rs:110]: Can we use an acronym here like `IVP`? `Network` is already a struct name representing the network we want to launch from the CLI options.

File: crates/light-client-prover/src/circuit/primitives.rs [hunk 21]
```diff
@@ -0,0 +1,347 @@
...
+            0,
+            decode_to_u32_array("3631d90630a3f0deb47f3a3411fe6e7ede1b0d86ad4216c75041e1a2020f009f"),
+        ),
+        (
+            5546000,
+            decode_to_u32_array("670b7ef87e7fab2ff2d46f38f71be524d42cc0c62da41884d3d41928b8c967d1"),
+        ),
+    ];
+
+    pub const DEVNET_INITIAL_BATCH_PROOF_METHOD_IDS: &[(u64, [u32; 8])] = &[
```
Comment (rakanalh) [inline crates/light-client-prover/src/circuit/primitives.rs]: Isn't this duplicating in a non-dynamic way what we do in `bin/citrea/src/guests.rs`?

File: crates/sovereign-sdk/rollup-interface/src/state_machine/da.rs [hunk 22]
```diff
@@ -166,8 +166,14 @@ pub trait DaSpec:
         + Send
         + Sync
         + Debug;
+
+    /// Decompress chunks to complete
+    fn decompress_chunks(complete_chunks: &[u8]) -> Result<Vec<u8>, DecompressError>;
 }
 
+/// Can't compress error
```
Comment (rakanalh) [inline crates/sovereign-sdk/rollup-interface/src/state_machine/da.rs]:
```suggestion
/// Decompression error
```

Comment (rakanalh) [reply crates/sovereign-sdk/rollup-interface/src/state_machine/da.rs]: This is not very useful IMO, Maybe just return `Result<Vec<u8>, ()>;` if there was an error, there is no value but the Err variant of `Result` would suffice to tell there was something wrong.

**Review by rakanalh — COMMENTED** [review]
Leaving my comments here as optional or to be addressed at a later stage.

File: bin/citrea/src/main.rs (hunk 20 above)
Comment (eyusufatik) [reply bin/citrea/src/main.rs:110]: Yeah, it’s that struct not a generic

File: crates/sovereign-sdk/rollup-interface/src/state_machine/da.rs (hunk 22 above)
Comment (eyusufatik) [reply crates/sovereign-sdk/rollup-interface/src/state_machine/da.rs]: I tried that but lint failed on that

File: bin/citrea/tests/bitcoin/bitcoin_test.rs (hunk 19 above)
Comment (eyusufatik) [reply bin/citrea/tests/bitcoin/bitcoin_test.rs:107]: it's due to that test being very flaky. never failed after i increased that time out :)

File: bin/citrea/src/main.rs (hunk 20 above)
Comment (eyusufatik) [reply bin/citrea/src/main.rs:110]: that is telling the compile to accept S with DaSpec that has 

InitialValueProvider<DaSpec> is implemented for network. a little weird I know.

File: crates/light-client-prover/src/circuit/primitives.rs (hunk 21 above)
Comment (eyusufatik) [reply crates/light-client-prover/src/circuit/primitives.rs]: I moved it over to here to have both compile time and run time decision on these constants

File: bin/citrea/tests/bitcoin/light_client_test.rs [hunk 23]
```diff
@@ -1150,13 +1160,17 @@ impl TestCase for VerifyChunkedTxsInLightClient {
         // After the block n+2 is processed we should see the state root updated
         let state_diff_130kb = create_random_state_diff(130);
 
+        let finalized_height = da.get_finalized_height(None).await?;
+        let l1_hash = da.get_block_hash(finalized_height - 3).await?;
```
Comment (yaziciahmet) [inline bin/citrea/tests/bitcoin/light_client_test.rs:1166]: why is this -3?

File: crates/bitcoin-da/src/spec/mod.rs [hunk 24]
```diff
@@ -46,4 +47,8 @@ impl DaSpec for BitcoinSpec {
     type CompletenessProof = Vec<TransactionWrapper>;
 
     type ShortHeaderProof = BitcoinHeaderShortProof;
+
+    fn decompress_chunks(complete_chunks: &[u8]) -> Result<Vec<u8>, DecompressError> {
+        borsh::from_slice(decompress_blob(complete_chunks).as_slice()).map_err(|_| DecompressError)
+    }
```
Comment (yaziciahmet) [inline crates/bitcoin-da/src/spec/mod.rs:53]: why is ths here? this can be a free function.

File: crates/common/src/backup/manager.rs [hunk 25]
```diff
@@ -23,17 +22,13 @@ pub struct BackupConfig {
 }
 
 impl BackupConfig {
-    fn new(node_kind: &str) -> Self {
-        let mut backup_dirs = vec![
+    fn new(_node_kind: &str) -> Self {
```
Comment (yaziciahmet) [inline crates/common/src/backup/manager.rs]: remove arg

File: crates/light-client-prover/src/circuit/primitives.rs [hunk 26]
```diff
@@ -0,0 +1,347 @@
...
+                (
+                    100,
+                    decode_to_u32_array(
+                        "7d28b6b03836af95eedd4c0aedfe93ed89d28356f0714dd01009a0b892585c03",
+                    ),
+                ),
+                (200, citrea_risc0_batch_proof::BATCH_PROOF_BITCOIN_ID),
+            ],
+        }
+    };
```
Comment (yaziciahmet) [inline crates/light-client-prover/src/circuit/primitives.rs]: didn't you say you are gonna fix this part in your pr?

File: crates/light-client-prover/src/circuit/primitives.rs
Comment (yaziciahmet) [inline crates/light-client-prover/src/circuit/primitives.rs:1]: This is not primitives this is constants or initial_values

File: crates/light-client-prover/src/circuit/primitives.rs [hunk 27]
```diff
@@ -0,0 +1,347 @@
...
+}
+
+#[cfg(feature = "native")]
+impl InitialValueProvider<MockDaSpec> for Network {
+    fn get_l2_genesis_root(&self) -> [u8; 32] {
+        match self {
+            Network::Mainnet
+            | Network::Testnet
+            | Network::Devnet
+            | Network::TestNetworkWithForks => {
```
Comment (yaziciahmet) [inline crates/light-client-prover/src/circuit/primitives.rs]: use _ => {...}
and do this check in each of the implemented trait methods.

File: crates/sovereign-sdk/rollup-interface/src/state_machine/da.rs [hunk 28]
```diff
@@ -166,8 +166,14 @@ pub trait DaSpec:
         + Send
         + Sync
         + Debug;
+
+    /// Decompress chunks to complete
+    fn decompress_chunks(complete_chunks: &[u8]) -> Result<Vec<u8>, DecompressError>;
```
Comment (yaziciahmet) [inline crates/sovereign-sdk/rollup-interface/src/state_machine/da.rs:171]: again, this is not ok

**Review by yaziciahmet — CHANGES_REQUESTED** [review]
Submitting a partial review to be able to move in parallel @eyusufatik
Continuing

File: crates/light-client-prover/src/circuit/accessors.rs [hunk 29]
```diff
@@ -0,0 +1,181 @@
...
+    pub fn exists(hash: [u8; 32], working_set: &mut WorkingSet<S>) -> bool {
+        // use `StateKey::singleton` as a hack to create no serialization key
+        let mut key = [0u8; 33]; // 1 prefix + 32 hash
+
+        key[0] = Self::PREFIX;
+        key[1..].copy_from_slice(&hash);
+
+        let p = Prefix::from_slice(&key);
+
+        let key = StorageKey::singleton(&p);
```
Comment (yaziciahmet) [inline crates/light-client-prover/src/circuit/accessors.rs]: singleton_owned

File: crates/light-client-prover/src/circuit/accessors.rs [hunk 30]
```diff
@@ -0,0 +1,181 @@
...
+
+pub struct BlockHashAccessor<S: Storage> {
+    phantom: core::marker::PhantomData<S>,
+}
+
+impl<S: Storage> BlockHashAccessor<S> {
+    const PREFIX: u8 = b'b';
+
+    pub fn exists(hash: [u8; 32], working_set: &mut WorkingSet<S>) -> bool {
+        // use `StateKey::singleton` as a hack to create no serialization key
```
Comment (yaziciahmet) [inline crates/light-client-prover/src/circuit/accessors.rs]: StorageKey
fix everywhere

File: crates/light-client-prover/src/circuit/accessors.rs [hunk 31]
```diff
@@ -0,0 +1,181 @@
...
+    pub fn get(wtxid: [u8; 32], working_set: &mut WorkingSet<S>) -> Option<Vec<u8>> {
+        // use `StateKey::singleton` as a hack to create no serialization key
+        let mut key = [0u8; 33]; // 1 prefix + 32 hash
+
+        key[0] = Self::PREFIX;
+        key[1..].copy_from_slice(&wtxid);
+
+        let p = Prefix::from_slice(&key);
+
+        let key = StorageKey::singleton(&p);
```
Comment (yaziciahmet) [inline crates/light-client-prover/src/circuit/accessors.rs]: singleton_owned

File: crates/light-client-prover/src/circuit/accessors.rs [hunk 32]
```diff
@@ -0,0 +1,181 @@
...
+
+        working_set.get(&key).map(|v| v.value().to_vec())
```
Comment (yaziciahmet) [inline crates/light-client-prover/src/circuit/accessors.rs]: return RefCount<[u8]> here, and only if needed the caller can convert it to Vec.

File: crates/sovereign-sdk/rollup-interface/src/state_machine/witness.rs [hunk 33]
```diff
@@ -42,6 +42,16 @@ impl Witness {
         let hint = self.hints.pop_front().expect("No more hints left");
         T::deserialize_reader(&mut hint.as_slice()).expect("Hint deserialization should never fail")
     }
+
+    /// Number of hints left
+    pub fn len(&self) -> usize {
```
Comment (yaziciahmet) [inline crates/sovereign-sdk/rollup-interface/src/state_machine/witness.rs]: call this remaining not len

File: crates/light-client-prover/src/circuit/accessors.rs [hunk 34]
```diff
@@ -0,0 +1,181 @@
...
+    }
+
+    /// Rerturns body of the chunk if it exists
+    /// None if it doesn't
```
Comment (yaziciahmet) [inline crates/light-client-prover/src/circuit/accessors.rs]: remove comment

File: crates/sovereign-sdk/adapters/mock-zkvm/src/lib.rs [hunk 35]
```diff
@@ -266,25 +265,12 @@ impl sov_rollup_interface::zk::Zkvm for MockZkGuest {
...
         serialized_proof: &[u8],
         code_commitment: &Self::CodeCommitment,
-    ) -> Result<(), Self::Error> {
-        let journal = Self::extract_raw_output(serialized_proof)?;
-
-        Self::verify(journal.as_slice(), code_commitment)
+    ) -> Result<T, Self::Error> {
+        Self::verify(serialized_proof, code_commitment)?;
+        let output = serialized_proof[33..].to_vec();
+        Ok(T::deserialize(&mut &*output)?)
```
Comment (yaziciahmet) [inline crates/sovereign-sdk/adapters/mock-zkvm/src/lib.rs]: &mut serialized_proof[33..] should work

File: crates/risc0/src/host.rs [hunk 36]
```diff
@@ -138,6 +138,13 @@ impl ZkvmHost for Risc0BonsaiHost {
         {
             if self.network == Network::TestNetworkWithForks {
                 env.env_var("ALL_FORKS", "1");
+                env.env_var("RISC0_DEV_MODE", "1");
+            }
+
+            // if we are testing, set guest env var to enable dev mode
+            // so that it verifies fake receipts
+            if self.network == Network::Nightly {
+                env.env_var("RISC0_DEV_MODE", "1");
```
Comment (yaziciahmet) [inline crates/risc0/src/host.rs]: use a match statement on network here, and you can even panic if its not either nightly or testnetworkwithforks

and shorten the comment to smh like "set this to verify fake receipts in guest". looking too bloated

File: crates/light-client-prover/src/circuit/mod.rs [hunk 37]
```diff
@@ -0,0 +1,453 @@
...
+use sov_rollup_interface::zk::light_client_proof::input::LightClientCircuitInput;
+use sov_rollup_interface::zk::light_client_proof::output::{
+    BatchProofInfo, LightClientCircuitOutput,
+};
+use sov_rollup_interface::zk::ZkvmGuest;
+use sov_rollup_interface::Network;
+
+use crate::utils::{collect_unchained_outputs, recursive_match_state_roots};
+
+// Until we transition to the new system completely, we name old/new
```
Comment (yaziciahmet) [inline crates/light-client-prover/src/circuit/mod.rs]: remove comment

File: crates/light-client-prover/src/circuit/mod.rs [hunk 38]
```diff
@@ -0,0 +1,453 @@
...
+                assert_eq!(
+                    input.light_client_proof_method_id,
+                    prev_output.light_client_proof_method_id,
+                );
+                Some(prev_output)
+            } else {
+                None
+            };
+
+        // make header chain verification and insert block hash to JMT
```
Comment (yaziciahmet) [inline crates/light-client-prover/src/circuit/mod.rs]: we don't insert block hash to jmt here, update comment

File: crates/light-client-prover/src/circuit/mod.rs [hunk 39]
```diff
@@ -0,0 +1,453 @@
...
+    pub fn run_circuit<DaV>(
+        &self,
+        da_verifier: DaV,
+        input: LightClientCircuitInput<DaV::Spec>,
+        l2_genesis_root: [u8; 32],
+        initial_batch_proof_method_ids: InitialBatchProofMethodIds,
+        batch_prover_da_public_key: &[u8],
+        method_id_upgrade_authority_da_public_key: &[u8],
+        network: Network,
+        storage: S,
```
Comment (yaziciahmet) [inline crates/light-client-prover/src/circuit/mod.rs]: carry this above constant params

File: bin/citrea/tests/bitcoin/light_client_test.rs (hunk 23 above)
Comment (eyusufatik) [reply bin/citrea/tests/bitcoin/light_client_test.rs:1166]: just wanted to try something else :)

File: crates/bitcoin-da/src/spec/mod.rs (hunk 24 above)
Comment (eyusufatik) [reply crates/bitcoin-da/src/spec/mod.rs:53]: this changes based on da. mock da, there is no compression, bitcoin da it's brotli.

on the light client proof circuit, event thought run_circuit has DaVerifier, run_l1_block didn't have one.

I didn't want to add lots of generics everywhere, and since run_l1_block already had access to DaSpec so i went this way

File: crates/light-client-prover/src/circuit/mod.rs [hunk 40]
```diff
@@ -0,0 +1,453 @@
...
+                            Some(body) => chunks.push(body),
+                            None => {
+                                println!(
+                                    "Unknown chunk in aggregate proof, wtxid={:?} skipping",
+                                    wtxid
+                                );
+                                continue;
+                            }
+                        }
+                    }
```
Comment (yaziciahmet) [inline crates/light-client-prover/src/circuit/mod.rs]: If an aggregate has an unknown chunk we should skip the aggregate, no? This will accept the aggregate even if there is a missing chunk.

continue should be for outer for loop here.

File: crates/light-client-prover/src/circuit/primitives.rs (hunk 26 above)
Comment (eyusufatik) [reply crates/light-client-prover/src/circuit/primitives.rs]: then I decided not to, since I realized all light client proof tests run with this set up.

File: crates/light-client-prover/src/circuit/mod.rs [hunk 41]
```diff
@@ -0,0 +1,453 @@
...
+                    println!("Found aggregate proof");
+                    if blob.sender().as_ref() != batch_prover_da_public_key {
+                        println!(
+                            "Aggregate proof sender is not batch prover, wtxid={:?}",
+                            blob.wtxid()
+                        );
+                        continue;
+                    }
+
+                    let mut chunks = Vec::with_capacity(wtxids.len());
```
Comment (yaziciahmet) [inline crates/light-client-prover/src/circuit/mod.rs]: Instead of having Vec<Vec<u8>> here, we can have Vec<u8>, and instead of pushing the chunks, we can extend_from_slice. This will get rid of the flatten().collect() we do below.

My previous comment about returning directly RefCount<[u8]> should also work with extend_from_slice suggestion.

File: bin/citrea/tests/bitcoin/light_client_test.rs (hunk 23 above)
Comment (eyusufatik) [reply bin/citrea/tests/bitcoin/light_client_test.rs:1166]: I mean other tests use finalized height. this one does not that's the only difference and no other purpose.

File: crates/light-client-prover/src/circuit/mod.rs [hunk 42]
```diff
@@ -0,0 +1,453 @@
...
+                "Witness prev root is wrong!"
+            );
+        } else {
+            // if running for the first time, we are going to be initializing the JMT
+            // so the genesis root must this constant
+            assert_eq!(
+                lcp_state_root_transition.init_root,
+                const_hex::decode_to_array(
+                    "5350415253455f4d45524b4c455f504c414345484f4c4445525f484153485f5f"
+                )
```
Comment (yaziciahmet) [inline crates/light-client-prover/src/circuit/mod.rs]: can we get this value as constant to somewhere else? EMPTY_STORAGE_ROOT or smh.

File: crates/light-client-prover/src/da_block_handler.rs [hunk 43]
```diff
@@ -162,169 +160,64 @@ where
             .set_l1_height_of_l1_hash(l1_hash, l1_height)
             .expect("Setting l1 height of l1 hash in ledger db");
 
-        let (mut da_data, inclusion_proof, completeness_proof) = self
+        let (da_data, inclusion_proof, completeness_proof) = self
             .da_service
             .extract_relevant_blobs_with_proof(&l1_block, DaNamespace::ToLightClientProver);
 
         let mut assumptions = vec![];
```
Comment (yaziciahmet) [inline crates/light-client-prover/src/da_block_handler.rs]: assumptions no longer need to be a vec, it can be Option<Vec<u8>>. This will also remove the assertion check of len = 0 || len = 1

File: crates/light-client-prover/src/da_block_handler.rs [hunk 44]
```diff
@@ -370,6 +261,9 @@ where
             stored_proof_output,
         )?;
 
+        // Only save after the proof is generated
+        self.storage_manager.finalize_storage(result.change_set);
```
Comment (yaziciahmet) [inline crates/light-client-prover/src/da_block_handler.rs]: Imo it makes more sense to do this before saving to ledger db

**Review by yaziciahmet — CHANGES_REQUESTED** [review]
One extra note:
- carry light-client-prover/src/utils.rs to circuit directory as well

Only remaining thing to review is light-client-prover/src/tests.

File: crates/sovereign-sdk/module-system/sov-state/src/zk_storage.rs [hunk 45]
```diff
@@ -69,20 +70,37 @@ impl Storage for ZkStorage {
...
+                    let key_bytes = key.key.clone();
+                    let value_bytes = value.as_ref().map(|v| v.value.clone());
+
+                    // Seems like we can get rid of the extra clone here
+                    diff.push((key_bytes, value_bytes.clone()));
+
+                    (key_hash, value_bytes)
+                })
+                .collect::<Vec<_>>()
+        };
```
Comment (yaziciahmet) [inline crates/sovereign-sdk/module-system/sov-state/src/zk_storage.rs]: else statement still accumlates diff

File: crates/light-client-prover/src/circuit/accessors.rs (hunk 29 above)
Comment (eyusufatik) [reply crates/light-client-prover/src/circuit/accessors.rs]: already handled in https://github.com/chainwayxyz/citrea/pull/2028/commits/0efc638c4a85ffdd237c1ba1085d1bbc3b41d0ee

File: crates/light-client-prover/src/circuit/accessors.rs (hunk 31 above)
Comment (eyusufatik) [reply crates/light-client-prover/src/circuit/accessors.rs]: already handled by https://github.com/chainwayxyz/citrea/pull/2028/commits/0efc638c4a85ffdd237c1ba1085d1bbc3b41d0ee

File: crates/sovereign-sdk/rollup-interface/src/state_machine/witness.rs (hunk 33 above)
Comment (eyusufatik) [reply crates/sovereign-sdk/rollup-interface/src/state_machine/witness.rs]: it's lints unfortunately if something has function is_empty() clippy requires a len() method.

File: crates/sovereign-sdk/module-system/sov-state/src/zk_storage.rs [hunk 46]
```diff
@@ -69,20 +70,37 @@ impl Storage for ZkStorage {
...
+        let batch = if accumulate_diff {
+            state_log
+                .iter_ordered_writes()
+                .map(|(key, value)| {
+                    let key_hash = KeyHash::with::<DefaultHasher>(key.key.as_ref());
+
+                    let key_bytes = key.key.clone();
+                    let value_bytes = value.as_ref().map(|v| v.value.clone());
+
+                    // Seems like we can get rid of the extra clone here
```
Comment (yaziciahmet) [inline crates/sovereign-sdk/module-system/sov-state/src/zk_storage.rs]: get rid of this comment, value_bytes is RefCount, no need to get rid of the extra clone anymore.

**Review by yaziciahmet — CHANGES_REQUESTED** [review]

File: crates/sovereign-sdk/rollup-interface/src/state_machine/witness.rs (hunk 33 above)
Comment (yaziciahmet) [reply crates/sovereign-sdk/rollup-interface/src/state_machine/witness.rs]: then remove is_empty and check is empty by remaining() == 0. len is confusing

File: crates/light-client-prover/src/circuit/mod.rs (hunk 40 above)
Comment (eyusufatik) [reply crates/light-client-prover/src/circuit/mod.rs]: yeah, i forgot to continue on outer loop

File: crates/light-client-prover/src/da_block_handler.rs (hunk 5 above)
Comment (yaziciahmet) [reply crates/light-client-prover/src/da_block_handler.rs:197]: then change the naming to create_storage_for_next_height

File: bin/citrea/tests/bitcoin/light_client_test.rs (hunk 23 above)
Comment (yaziciahmet) [reply bin/citrea/tests/bitcoin/light_client_test.rs:1166]: remove it, it looks like it has some special purpose and is confusing, spent a lot of time trying to decode this

File: crates/bitcoin-da/src/spec/mod.rs (hunk 24 above)
Comment (yaziciahmet) [reply crates/bitcoin-da/src/spec/mod.rs:53]: then is it possible to remove decompress chunks from DaVerifier and just keep it here at least

File: crates/light-client-prover/src/circuit/initial_values.rs [hunk 47]
```diff
@@ -0,0 +1,344 @@
...
+        mockda::INITIAL_BATCH_PROOF_METHOD_IDS.to_vec()
+    }
+
+    fn batch_prover_da_public_key(&self) -> [u8; 33] {
+        mockda::BATCH_PROVER_DA_PUBLIC_KEY
+    }
+
+    fn method_id_upgrade_authority_da_public_key(&self) -> [u8; 33] {
+        mockda::METHOD_ID_UPGRADE_AUTHORITY_DA_PUBLIC_KEY
+    }
```
Comment (yaziciahmet) [inline crates/light-client-prover/src/circuit/initial_values.rs]: make the nightly check on each of these methods. no need for a match, just go assert_eq(network, nightly)

**Review by yaziciahmet — DISMISSED** [review]

File: crates/sovereign-sdk/adapters/mock-zkvm/src/lib.rs (hunk 35 above)
Comment (yaziciahmet) [reply crates/sovereign-sdk/adapters/mock-zkvm/src/lib.rs]: &mut &serialized_proof[33..]

**Comment by yaziciahmet** [comment]
It would be great to have a bitcoin-e2e test for unchained batch proofs, can you create an issue for that?

File: crates/bitcoin-da/src/spec/mod.rs (hunk 24 above)
Comment (eyusufatik) [reply crates/bitcoin-da/src/spec/mod.rs:53]: decided to add comment instead

File: crates/light-client-prover/src/circuit/accessors.rs [hunk 48]
```diff
@@ -0,0 +1,187 @@
...
+
+        let key = StorageKey::singleton_owned(p);
+
+        let value: StorageValue = body.into();
+
+        working_set.set(&key, value);
+    }
+}
+
+// TODO: write raw accessor tests with JMT
```
Comment (yaziciahmet) [inline crates/light-client-prover/src/circuit/accessors.rs]: is this comment needed still?

**Review by ercecan — APPROVED** [review]
