### PR TITLE
fix: Misplaced log in boundless

### LINKED ISSUE #3124: False log bug in boundless
discovered by @exeokan 

https://github.com/chainwayxyz/citrea/blob/f0497402ee89afd3ec96582ebfcba6b8df51b331/crates/risc0/src/host/boundless.rs#L460-L474

In these lines `Resubmit boundless proving session Failed with job id` log is printed even if the resubmit is a success that log should be captured in an else block

also no need for continue in that block either

### PR DESCRIPTION
**Pull request by ercecan**
# Description

## Linked Issues
- Fixes #3124

### CODE REVIEW

File: crates/risc0/src/host/boundless.rs [hunk 1]
```diff
@@ -542,19 +542,27 @@ impl BoundlessProver {
...
-                                tracing::info!(
-                                    "Resubmit boundless proving session Failed with job id: {}, and boundless request id: {} retrying...",
-                                    job_id,
-                                    request_id
-                                );
-                                continue;
+                                match res {
+                                    ResubmitResult::Retry => {
+                                        // Retry resubmission after a delay
+                                        let delay_duration = Duration::from_secs(10);
```
Comment (exeokan) [inline crates/risc0/src/host/boundless.rs]: `delay_duration` could be a constant in this file

**Review by exeokan — CHANGES_REQUESTED** [review]
rest lgtm

File: crates/risc0/src/host/boundless.rs (hunk 1 above)
Comment (eyusufatik) [reply crates/risc0/src/host/boundless.rs]: config var that defaults to 10 secs

**Review by eyusufatik — CHANGES_REQUESTED** [review]

File: crates/risc0/src/host/boundless.rs (hunk 1 above)
Comment (ercecan) [reply crates/risc0/src/host/boundless.rs]: agreed with @eyusufatik to use constant

**Review by eyusufatik — DISMISSED** [review]

**Review by eyusufatik — APPROVED** [review]

**Review by exeokan — APPROVED** [review]
