### PR TITLE
fix: add mantissa size check

### LINKED ISSUE #2814: Add size check to mantissa
Add [this](https://github.com/rust-bitcoin/rust-bitcoin/blob/a0cb9bfc648ded8839b7897e81d7a9d73623a636/bitcoin/src/pow.rs#L187) check to [here](https://github.com/chainwayxyz/citrea/blob/7b7c9dc1ab7ab3c419eb36aee8ae077eee450b04/crates/bitcoin-da/src/verifier.rs#L604)

### PR DESCRIPTION
**Pull request by exeokan**
# Description
Sets the target to zero if mantissa sign bit is set.

## Linked Issues
- Fixes #2814

### CODE REVIEW

File: crates/bitcoin-da/src/verifier.rs [hunk 1]
```diff
@@ -605,6 +605,11 @@ fn bits_to_target(bits: u32) -> [u8; 32] {
     let size = (bits >> 24) as usize;
     let mantissa = bits & 0x00ffffff;
 
+    // Mantissa should not be negative
```
Comment (ozankaymak) [inline crates/bitcoin-da/src/verifier.rs]: I believe we need to explain why there is a difference here for Rust Bitcoin and Bitcoin core implementation (u32, i32) because u32 can never be negative. Maybe also a link for CompactTarget etc.

**Review by ozankaymak — CHANGES_REQUESTED** [review]

**Review by eyusufatik — APPROVED** [review]

**Review by ozankaymak — APPROVED** [review]

File: crates/bitcoin-da/src/verifier.rs (hunk 1 above)
Comment (exeokan) [reply crates/bitcoin-da/src/verifier.rs]: edited comment
