### PR TITLE
Handle SkippapleError in fullnode pending proofs

### LINKED ISSUE #2735: Fullnode: Pending proof unrecoverable error is not discarded
Fails with :`Failed to process pending proof with index 2403-2403: Other(Failed to verify proof: claim digest does not match the expected digest 70106ee09fea6dfd808f2523d71489578c3d150a0b2f3da546322ce27628d7c7; expected 698f1b8829804c110f339a7f2c45f7dba75ba3689e244609dc922e84c80955f4. Skipping it...)` but is kept as pending

### PR DESCRIPTION
**Pull request by jfldde**
# Description

- Discard errors in `process_zk_proof`

## Linked Issues
- Fixes #2735

### CODE REVIEW

File: crates/fullnode/src/da_block_handler.rs [hunk 1]
```diff
@@ -577,7 +577,9 @@ where
             code_commitment,
             network_to_dev_mode(self.network),
         )
-        .map_err(|err| anyhow!("Failed to verify proof: {:?}. Skipping it...", err))?;
+        .map_err(|err| {
```
Comment (eyusufatik) [inline crates/fullnode/src/da_block_handler.rs]: should we maybe return Ok(Discarded) like we do on sequencer commitments 🤔

**Review by eyusufatik — APPROVED** [review]
I mean it still works with the error type ofc

File: crates/fullnode/src/da_block_handler.rs (hunk 1 above)
Comment (jfldde) [reply crates/fullnode/src/da_block_handler.rs]: Yes, switching to this instead

**Review by ercecan — APPROVED** [review]
