### PR TITLE
Fix lack of precompiles in simulation queries

### LINKED ISSUE #2183: `eth_call` does not have same custom precompiles
## Summary
As we don't append revm citrea handler to revm inside eth_call's we don't have the same precompile set as normal execution.

### PR DESCRIPTION
**Pull request by eyusufatik**
# Description
On endpoints such as 

- eth_call
- eth_createAccessList
- eth_estimateGas

Uses citrea evm handler so that everything works the same with normal transaction execution.

## Linked Issues
Fixes #2183 

## Testing
Describe how these changes were tested. If you've added new features, have you added unit tests?

## Docs
Describe where this code is documented. If it changes a documented interface, have the docs been updated?

### CODE REVIEW

File: crates/evm/src/query.rs [hunk 1]
```diff
@@ -709,11 +712,14 @@ impl<C: sov_modules_api::Context> Evm<C> {
         // can consume the list since we're not using the request anymore
         let initial = request.access_list.take().unwrap_or_default();
 
+        // TODO: update here.
```
Comment (eyusufatik) [inline crates/evm/src/query.rs]: todo

File: crates/evm/src/evm/handler.rs [hunk 2]
```diff
@@ -240,6 +240,7 @@ where
         self.inspector.create_end(context, inputs, outcome)
     }
     fn selfdestruct(&mut self, contract: Address, target: Address, value: U256) {
+        // why not  self.inspector.selfdestruct(contract, target, value) ?
```
Comment (eyusufatik) [inline crates/evm/src/evm/handler.rs]: @kpp

Comment (kpp) [reply crates/evm/src/evm/handler.rs]: Do it if you can do that. It wasnt available on prev rust versions

**Review by kpp — APPROVED** [review]
