### PR TITLE
fix authority change sov nonce increase

### LINKED ISSUE #1967: Nonce not increased when multiple sov txs are part of the same block

### PR DESCRIPTION
**Pull request by ercecan**
# Description

## Linked Issues
- Fixes #1967

### CODE REVIEW

File: crates/sequencer/src/runner.rs [hunk 1]
```diff
@@ -832,10 +835,14 @@ where
...
         spec_id: SpecId,
+        increment_nonce: bool,
     ) -> anyhow::Result<Transaction> {
         // if a batch failed need to refetch nonce
         // so sticking to fetching from state makes sense
-        let nonce = self.get_nonce(working_set, spec_id)?;
+        let mut nonce = self.get_nonce(working_set, spec_id)?;
+        if increment_nonce {
+            nonce += 1;
+        }
```
Comment (yaziciahmet) [inline crates/sequencer/src/runner.rs]: are we sure about this? get_nonce seems to return a 0 on nonexistent, and we will create the first tx with  1, but nonce should start from 0

File: crates/sequencer/src/runner.rs [hunk 2]
```diff
@@ -512,7 +515,7 @@ where
             if next_fork.spec_id == SpecId::Fork2
                 && soft_confirmation_info.l2_height + 1 == next_fork.activation_height
             {
-                let (signed_blob, signed_tx) = self.update_sequencer_authority(&mut working_set, soft_confirmation_info.current_spec()).expect("Should create and sign soft confirmation rule enforcer authority change call messages");
+                let (signed_blob, signed_tx) = self.update_sequencer_authority(&mut working_set, soft_confirmation_info.current_spec(), !txs.is_empty()).expect("Should create and sign soft confirmation rule enforcer authority change call messages");
```
Comment (yaziciahmet) [inline crates/sequencer/src/runner.rs]: why only increment nonce when txs not empty

**Review by yaziciahmet — CHANGES_REQUESTED** [review]

File: crates/sequencer/src/runner.rs
Comment (eyusufatik) [inline crates/sequencer/src/runner.rs:1]: i think the better solution and long term better api would be to have sign_tx accept nonce as param and we call get_nonce outside and pass it to the function. 

that way we have better control of the nonce

**Review by eyusufatik — CHANGES_REQUESTED** [review]

File: crates/sequencer/src/runner.rs
Comment (ercecan) [reply crates/sequencer/src/runner.rs:1]: will do

File: crates/sequencer/src/runner.rs (hunk 1 above)
Comment (ercecan) [reply crates/sequencer/src/runner.rs]: That'll only work for a specific case, but it's a bad api rn so I'll just pass nonce to the fn as Esad said
