### PR TITLE
fix sequencer resubmission logic

### LINKED ISSUE #1998: Update sequencer commitment resubmission logic
Right now the sequencer commitment resubmission logic works like this:
- We get our pendind commitments from ledger dn
- We get the submitted pending commitments from mempool
- We get the last commitment l1 height (which is the da slot height of latest l2 block of latest commitment that was submitted)
- We scan starting from that l1 height to the head of l1 and get mined commitments as well
- We iterate over our pending commitments from db if we see a commitment which is already mined or in mempool we remove it from db else we resubmit

This won't work now because after fork2 there is no da data such as da slot height in l2 block

Thus we need to change the logic

### PR DESCRIPTION
**Pull request by eyusufatik**
# Description

## Linked Issues
Closes #1998

## Testing
Describe how these changes were tested. If you've added new features, have you added unit tests?

## Docs
Describe where this code is documented. If it changes a documented interface, have the docs been updated?

### CODE REVIEW

File: crates/sequencer/src/commitment/mod.rs [hunk 1]
```diff
@@ -196,6 +202,10 @@ where
                 .as_secs_f64(),
         );
 
+        ledger_db
+            .put_commitment_by_index(&commitment)
+            .map_err(|_| anyhow!("Sequencer: Failed to store sequencer commitment by index"))?;
+
```
Comment (yaziciahmet) [inline crates/sequencer/src/commitment/mod.rs:208]: is there any specific reason you carried saving the commitment after da submission?

File: crates/sequencer/src/commitment/mod.rs [hunk 2]
```diff
@@ -207,26 +217,53 @@ where
...
             pending_mempool_commitments
         );
 
-        let last_commitment_l1_height = self
-            .ledger_db
-            .get_l1_height_of_last_commitment()?
-            .unwrap_or(SlotNumber(1));
-        let mined_commitments = self
-            .get_mined_commitments_from(last_commitment_l1_height)
+        // to determine which L1 block to start scannign from
```
Comment (yaziciahmet) [inline crates/sequencer/src/commitment/mod.rs]: scanning

File: crates/sequencer/src/commitment/mod.rs [hunk 3]
```diff
@@ -207,26 +217,53 @@ where
...
+            let l2_height = {
+                let last_commitment = self.ledger_db.get_last_commitment()?;
+
+                if let Some(last_commitment) = last_commitment {
+                    last_commitment.l2_end_block_number
+                } else {
+                    // if no commitment yet, just use block number 1
+                    1
+                }
+            };
```
Comment (yaziciahmet) [inline crates/sequencer/src/commitment/mod.rs]: let l2_height = ledger_db.get_last_commitment()?.map(...).unwrap_or(1);

File: crates/sequencer/src/commitment/mod.rs [hunk 4]
```diff
@@ -207,26 +217,53 @@ where
...
+            // set state to end of evm block l2_height
+            working_set.set_archival_version(l2_height + 1);
+
+            let l1_height = get_last_l1_height_in_light_client(
+                &Evm::<DefaultContext>::default(),
+                &mut working_set,
+            )
+            .expect("There must be a last l1 height");
+
+            l1_height.to::<u64>() + 1u64
```
Comment (yaziciahmet) [inline crates/sequencer/src/commitment/mod.rs]: + 1 (no need for u64 postfix)

Comment (yaziciahmet) [inline crates/sequencer/src/commitment/mod.rs]: + 1 (no need for u64 postfix)

File: crates/sequencer/src/commitment/mod.rs [hunk 5]
```diff
@@ -236,21 +273,33 @@ where
...
+
         for pending_db_comm in pending_db_commitments {
             if pending_commitments_to_remove
                 .iter()
                 .any(|commitment| commitment.index == pending_db_comm.index)
             {
+                // thins pending commiment is either mined or in the L1 mempool
+                // so we can delete it from the pending db
+                // and also update last sequencer commitment l2 height
+
```
Comment (yaziciahmet) [inline crates/sequencer/src/commitment/mod.rs:286]: I think this is easy to understand from the variable names and fns already. comment can be removed.

File: crates/sequencer/src/commitment/mod.rs [hunk 6]
```diff
@@ -306,18 +355,22 @@ where
 
     async fn get_mined_commitments_from(
         &self,
-        _da_height: SlotNumber,
+        start_height: u64,
     ) -> anyhow::Result<Vec<SequencerCommitment>> {
+        info!(
```
Comment (yaziciahmet) [inline crates/sequencer/src/commitment/mod.rs:355]: not info, debug

**Review by yaziciahmet — CHANGES_REQUESTED** [review]

File: crates/sequencer/src/commitment/mod.rs (hunk 4 above)
Comment (yaziciahmet) [reply crates/sequencer/src/commitment/mod.rs]: dont know how it got duplicated

File: crates/sequencer/src/commitment/mod.rs (hunk 1 above)
Comment (eyusufatik) [reply crates/sequencer/src/commitment/mod.rs:208]: it makes more sense that way because if somehow sequencer dies right before commitment is sent to mempool, we can use pending to restruct but the commitment by index table being filled might be a little problematic.


It used to be the case that we were not waiting on DA send, but the commitment service runs in a different task now so we don't need to care about waiting on DA tx mining.

File: crates/sequencer/src/commitment/mod.rs (hunk 5 above)
Comment (eyusufatik) [reply crates/sequencer/src/commitment/mod.rs:286]: everytime I read this code again I have to spend time understanding the underlying logic. so comment is fine.

File: crates/sequencer/src/commitment/mod.rs (hunk 6 above)
Comment (eyusufatik) [reply crates/sequencer/src/commitment/mod.rs:355]: imo info, esp.given that we had problems with this before, it helps to have these kind of logs (and also this runs only once)

**Review by yaziciahmet — APPROVED** [review]
