### PR TITLE
Full node halts on merkle root mismatch to behave like lcp

### LINKED ISSUE #2349: Full node should halt as lcp does after a sequencer commitment with wrong merkle root
Currently there is no way to verify the merkle root of a sequencer commitment in the lcp circuit, when it sees a sequencer commitment with an index it has never seen before it will just save it to its state. When the time comes to process a proof with that false commitment it will not be able to verify the proof thus the lcp will halt.

According to this we expect the full node to behave the same way so it should also halt in that situation

### PR DESCRIPTION
**Pull request by ercecan**
# Description

## Linked Issues
- Fixes #2349

### CODE REVIEW

File: crates/fullnode/src/da_block_handler.rs [hunk 1]
```diff
@@ -501,11 +538,11 @@ where
                 })?;
 
         if start_state_root.as_ref() != initial_state_root.as_ref() {
-            return Err(anyhow!(
-                    "Proof verification: For a known and verified sequencer commitment. Pre state root mismatch - expected 0x{} but got 0x{}. Skipping proof.",
-                    hex::encode(initial_state_root),
-                    hex::encode(start_state_root)
-                ).into());
+            return Err(SkippableError::Proof(ProofError::PreStateRootMismatch(
```
Comment (eyusufatik) [inline crates/fullnode/src/da_block_handler.rs:541]: should this really be skippable? what happens on lcp

**Review by eyusufatik — APPROVED** [review]

File: crates/fullnode/src/da_block_handler.rs (hunk 1 above)
Comment (ercecan) [reply crates/fullnode/src/da_block_handler.rs:541]: I mean this check is after the previous commitment merkle root verification and previous commitment hash check
If all are valid this normally should not happen
