### PR TITLE
L2Syncer enhancements

### LINKED ISSUE #2629: Improve L2Syncer error handling
- Should define a proper error enum and act on different variants when failing to `process_l2_block`

### PR DESCRIPTION
**Pull request by jfldde**
# Description

- L2SyncerError enum 
- Add a `MAX_BUFFER_SIZE` bound to buffer
- Panic and exit tasks on unrecoverable L2Syncer error
- Only retry on recoverable error (only missing DA block for now)
- Refactor and move to L2 subfolder

## Linked Issues
- Fixes #2629

### CODE REVIEW

File: crates/common/src/l2/mod.rs [hunk 1]
```diff
@@ -299,13 +321,18 @@ async fn sync_l2(
...
-        start_l2_height += l2_blocks.len() as u64;
-
-        block_buffer.lock().await.extend_blocks(l2_blocks);
+        let blocks_len = l2_blocks.len() as u64;
+        match block_buffer.lock().await.extend_blocks(l2_blocks) {
+            Ok(()) => start_l2_height += blocks_len,
+            Err(_) => {
+                sleep(Duration::from_secs(2)).await;
+                continue;
+            }
```
Comment (ercecan) [inline crates/common/src/l2/mod.rs]: Maybe also put a warn!(e) here because this cannot happen very often right?

**Review by ercecan — APPROVED** [review]
