### PR TITLE
Erce/fix rpc error message

### LINKED ISSUE #383: EVM RPC: compatible errors
## Summary

I ran uniswap tests against avail and got a nice error:

1. `anvil --port 12345 --chain-id 5655`
2. `npx hardhat run --network sov scripts/01_deploy.js`

Error is this:

```
    at ......bin/citrea/tests/evm/uniswap/node_modules/@ethersproject/providers/src.ts/json-rpc-provider.ts:265:24
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  reason: 'insufficient funds for intrinsic transaction cost',
  code: 'INSUFFICIENT_FUNDS',
  error: ProviderError: Insufficient funds for gas * price + value
  ```

However when I ran hardhat tests against our node and got this error from sequencer:

```
2024-04-15T12:06:36.336554Z TRACE method_call{method="eth_sendRawTransaction"}: jsonrpsee_core::tracing: send="{\"jsonrpc\":\"2.0\",\"error\":{\"code\":-32003,\"message\":\"ETH_RPC_ERROR\",\"data\":\"[0x85b0ac98e84e898a5778488d1f95d617fad90b5f599ffafeadd4b15004d1c75d]: insufficient gas price to replace existing transaction\"},\"id\":19}"
```

And in hardhat the error looks like this:

```
ProviderError: ETH_RPC_ERROR
    at HttpProvider.request (......bin/citrea/tests/evm/uniswap/node_modules/hardhat/src/internal/core/providers/http.ts:88:21)
```

So our RPC errors are not properly recognized by hardhat/ethers. We need to fix it.

### PR DESCRIPTION
**Pull request by ercecan**
# Description
**Merge after #385 is merged**
Fixes rpc error messages to be compatible

## Linked Issues
- Fixes #383

### CODE REVIEW

File: crates/sequencer/src/rpc.rs [hunk 1]
```diff
@@ -42,7 +41,12 @@ pub(crate) fn create_rpc_module<C: sov_modules_api::Context>(
             .mempool
             .add_external_transaction(pool_transaction)
             .await
-            .map_err(|e| to_jsonrpsee_error_object(e, ETH_RPC_ERROR))?;
+            .map_err(|e| {
+                let err = RpcPoolError::from(e);
+                let error_string = err.to_string();
+                to_jsonrpsee_error_object(&error_string, err)
```
Comment (ercecan) [inline crates/sequencer/src/rpc.rs:47]: &err.to_string()

**Review by ercecan — COMMENTED** [review]
1 comment

File: crates/sovereign-sdk/module-system/sov-modules-api/src/utils.rs [hunk 2]
```diff
@@ -7,7 +7,7 @@ pub fn generate_address<C: Context>(key: &str) -> <C as Spec>::Address {
     C::Address::from(hash)
 }
 
-pub fn to_jsonrpsee_error_object(err: impl ToString, message: &str) -> ErrorObjectOwned {
+pub fn to_jsonrpsee_error_object(message: &str, err: impl ToString) -> ErrorObjectOwned {
```
Comment (kpp) [inline crates/sovereign-sdk/module-system/sov-modules-api/src/utils.rs:10]: Are you sure we can't use some generic reth error instead of 2 args?

Comment (ercecan) [reply crates/sovereign-sdk/module-system/sov-modules-api/src/utils.rs:10]: I will be trying that instead of using this function at all, but for some custom cases we will need this ofc

File: crates/ethereum-rpc/src/lib.rs [hunk 3]
```diff
@@ -214,7 +212,7 @@ fn register_rpc_methods<C: sov_modules_api::Context, Da: DaService>(
 
         // convert block count to u64 from hex
         let block_count = u64::from_str_radix(&block_count[2..], 16)
-            .map_err(|e| to_jsonrpsee_error_object(e, ETH_RPC_ERROR))?;
+            .map_err(|e| to_jsonrpsee_error_object(&e.to_string(), e))?;
```
Comment (eyusufatik) [inline crates/ethereum-rpc/src/lib.rs:215]: can you use ethapierror::invalidparams here
or smth like that

File: crates/ethereum-rpc/src/lib.rs [hunk 4]
```diff
@@ -554,16 +545,15 @@ fn register_rpc_methods<C: sov_modules_api::Context, Da: DaService>(
                 BlockNumberOrTag::Latest => convert_u256_to_u64(evm.block_number(&mut working_set)?),
                 _ => {
                     return Err(to_jsonrpsee_error_object(
```
Comment (eyusufatik) [inline crates/ethereum-rpc/src/lib.rs:547]: EthApiError::Unsupported("Earliest, pending, safe and finalized are not supported for debug_traceBlockByNumber").into()

File: crates/ethereum-rpc/src/lib.rs [hunk 5]
```diff
@@ -776,13 +761,13 @@ fn register_rpc_methods<C: sov_modules_api::Context, Da: DaService>(
...
                                     .await
-                                    .map_err(|e| to_jsonrpsee_error_object(e, ETH_RPC_ERROR))?;
+                                    .map_err(|e| to_jsonrpsee_error_object(&e.to_string(), e))?;
 
                                 Ok::<Option<reth_rpc_types::Transaction>, ErrorObjectOwned>(tx)
                             }
                             Err(e) => {
                                 // return error
-                                Err(to_jsonrpsee_error_object(e, ETH_RPC_ERROR))
+                                Err(to_jsonrpsee_error_object(&e.to_string(), e))
```
Comment (eyusufatik) [inline crates/ethereum-rpc/src/lib.rs:770]: e should work 
or e.into()

File: crates/ethereum-rpc/src/lib.rs [hunk 6]
```diff
@@ -730,7 +715,7 @@ fn register_rpc_methods<C: sov_modules_api::Context, Da: DaService>(
                     .send_raw_tx(data)
                     .await;
 
-                tx_hash.map_err(|e| to_jsonrpsee_error_object(e, ETH_RPC_ERROR))
+                tx_hash.map_err(|e| to_jsonrpsee_error_object(&e.to_string(), e))
```
Comment (eyusufatik) [inline crates/ethereum-rpc/src/lib.rs:718]: I believe we return PoolError from sequencer

which can be converted to EthApiError

which impls. into JsonRPSeeError 

so proper casting here make it work very well.

File: crates/sovereign-sdk/full-node/sov-sequencer/src/lib.rs
Comment (eyusufatik) [inline crates/sovereign-sdk/full-node/sov-sequencer/src/lib.rs:1]: rollback

File: crates/ethereum-rpc/src/lib.rs [hunk 7]
```diff
@@ -755,7 +740,7 @@ fn register_rpc_methods<C: sov_modules_api::Context, Da: DaService>(
                             .unwrap()
                             .get_tx_by_hash(hash, Some(true))
                             .await
-                            .map_err(|e| to_jsonrpsee_error_object(e, ETH_RPC_ERROR))?;
+                            .map_err(|e| to_jsonrpsee_error_object(&e.to_string(), e))?;
```
Comment (eyusufatik) [inline crates/ethereum-rpc/src/lib.rs:743]: same thing

**Review by eyusufatik — CHANGES_REQUESTED** [review]

File: crates/ethereum-rpc/src/lib.rs [hunk 8]
```diff
@@ -832,7 +834,7 @@ pub fn get_latest_git_tag() -> Result<String, ErrorObjectOwned> {
     let latest_tag_commit = Command::new("git")
         .args(["rev-list", "--tags", "--max-count=1"])
         .output()
-        .map_err(|e| to_jsonrpsee_error_object(e, "Failed to get version"))?;
+        .map_err(|e| to_jsonrpsee_error_object("Failed to get version", e))?;
```
Comment (eyusufatik) [inline crates/ethereum-rpc/src/lib.rs:837]: FULL_NODE_ERROR

**Review by eyusufatik — CHANGES_REQUESTED** [review]

File: crates/ethereum-rpc/src/lib.rs [hunk 9]
```diff
@@ -641,9 +625,7 @@ fn register_rpc_methods<C: sov_modules_api::Context, Da: DaService>(
                         opts.clone(),
                         Some(trace_index as usize),
                         &mut working_set,
-                    )
-                    .map_err(|e| to_jsonrpsee_error_object(e, ETH_RPC_ERROR))?
-                        [trace_index as usize]
+                    )?[trace_index as usize]
```
Comment (kpp) [inline crates/ethereum-rpc/src/lib.rs:628]: Ooof. Maybe refactor a little bit?

File: crates/ethereum-rpc/src/lib.rs [hunk 10]
```diff
@@ -749,15 +735,21 @@ fn register_rpc_methods<C: sov_modules_api::Context, Da: DaService>(
...
                             .as_ref()
                             .unwrap()
                             .get_tx_by_hash(hash, Some(true))
                             .await
-                            .map_err(|e| to_jsonrpsee_error_object(e, ETH_RPC_ERROR))?;
-
-                        Ok::<Option<reth_rpc_types::Transaction>, ErrorObjectOwned>(tx)
+                        {
+                            Ok(tx) => {
+                                Ok::<Option<reth_rpc_types::Transaction>, ErrorObjectOwned>(tx)
```
Comment (kpp) [inline crates/ethereum-rpc/src/lib.rs:746]: I don't like the compiler can't deduce generic types for Ok/Err. Is it really the case here?

File: crates/sequencer-client/src/lib.rs [hunk 11]
```diff
@@ -44,27 +44,28 @@ impl SequencerClient {
     }
 
     /// Sends raw tx to sequencer
-    pub async fn send_raw_tx(&self, tx: Bytes) -> anyhow::Result<H256> {
-        let tx_hash: H256 = self
+    pub async fn send_raw_tx(&self, tx: Bytes) -> Result<H256, Error> {
+        let tx_hash: Result<H256, Error> = self
```
Comment (kpp) [inline crates/sequencer-client/src/lib.rs:48]: Do we need explicit type here along with a `tx_hash` var?

File: crates/sequencer/src/rpc.rs [hunk 12]
```diff
@@ -81,7 +80,7 @@ pub(crate) fn create_rpc_module<C: sov_modules_api::Context>(
 
                     match evm.get_transaction_by_hash(hash, &mut working_set) {
                         Ok(tx) => Ok::<Option<reth_rpc_types::Transaction>, ErrorObjectOwned>(tx),
```
Comment (kpp) [inline crates/sequencer/src/rpc.rs:82]: Same explicit type here.

**Review by eyusufatik — DISMISSED** [review]

File: crates/ethereum-rpc/src/lib.rs [hunk 13]
```diff
@@ -635,17 +619,13 @@ fn register_rpc_methods<C: sov_modules_api::Context, Da: DaService>(
...
-                        [trace_index as usize]
-                        .clone(),
-                );
+                let traces = evm.trace_block_transactions_by_number(
+                    block_number,
+                    opts.clone(),
+                    Some(trace_index as usize),
+                    &mut working_set,
+                )?;
+                return Ok(traces[trace_index as usize].clone());
```
Comment (kpp) [inline crates/ethereum-rpc/src/lib.rs:628]: There is a possible DOS via panic because of out of bound

**Review by kpp — APPROVED** [review]

**Review by eyusufatik — APPROVED** [review]
