### PR TITLE
Invalidate Soft Confirmation on sov-module errors

### LINKED ISSUE #1048: Refactor SoftConfirmationError enum
https://github.com/chainwayxyz/citrea/pull/1046#discussion_r1734387034

### LINKED ISSUE #1061: Don't panic, return Err on sov-tx deserializtion or signature errors
see this issue in codebase

### LINKED ISSUE #1438: Reconsider failing on any tx fail in evm

### LINKED ISSUE #1493: apply_sov_txs_inner - remove txreceipts
We don't need to store sov-tx receipts. We also have to remove `TransactionDigest` because we don't need to calc `raw_tx_hash` anymore.

### PR DESCRIPTION
**Pull request by eyusufatik**
# Description
any failing (I don't mean reverting here, failing) evm tx will make the soft confirmation invalid.

The way I handled the hash bug fix should be changed into a better one imo.

At the beginning of the project we thought when we enabled forced transactions we would need to run them along soft confirmations. However, they can be treated differently. All the workaround and ignoring errored transactions makes a lot of stuff much harder. e.g. we have to have weird workaround accessory maps for block bulding etc.

Another goal of this pr is to fix error handling and propogation in the STF   

Closes #1438 
Closes #1061
Closes #1048

TODO
- [x] before merging: Double check working_set reverts in stf blueprint. one thing to notice is that a sov-tx erroring now means reverting the whole soft confirmation. Resolved: we don't checkpoint in stf now, becuase we invalidate on error. way less memcpy in general.
- [x] #1493 
- [x] Check ZK side checkpointing in stf

however, in evm unit tests, we keep working on a working set after a failing evm call. such as going over a block gas limit.  now the working set reverting must happen **explicitly**.

### CODE REVIEW

File: crates/evm/src/evm/executor.rs [hunk 1]
```diff
@@ -111,34 +106,25 @@ pub(crate) fn execute_multiple_tx<
...
-            Ok(result_and_state) => result_and_state,
-            Err(e) => {
-                native_error!(error = %e, "Transaction failed");
-                tx_results.push(Err(e));
-                continue;
-            }
-        };
+        let result_and_state = evm.transact(tx).map_err(|e| match e {
+            // only custom error we use is for not enough funds for L1 fee
+            EVMError::Custom(_) => SoftConfirmationModuleCallError::EvmNotEnoughFundsForL1Fee,
```
Comment (ercecan) [inline crates/evm/src/evm/executor.rs]: What happens if we have multiple custom errors?

File: crates/sequencer/src/runner.rs [hunk 2]
```diff
@@ -302,37 +299,69 @@ where
...
+                                               if block_gas_limit - cumulative_gas < MIN_TRANSACTION_GAS {
+                                                break;
+                                               } else {
+                                                working_set_to_discard = working_set.revert().to_revertable();
+                                                continue;
+                                               }
+                                            },
+                                            // we configure mempool to never accept blob transactions
+                                            // to mitigate potential bugs in reth-mempool we should look into continue instead of panicking here
+                                            sov_modules_api::SoftConfirmationModuleCallError::EvmBlobGasUsedExceedsBlockGasLimit => panic!("got blob tx from mempool"),
```
Comment (ercecan) [inline crates/sequencer/src/runner.rs:341]: Why is this a panic?

File: crates/sovereign-sdk/module-system/sov-modules-stf-blueprint/src/stf_blueprint.rs [hunk 3]
```diff
@@ -129,48 +128,39 @@ where
...
             };
             // Commit changes after pre_dispatch_tx_hook
-            sc_workspace = sc_workspace.checkpoint().to_revertable();
+            // sc_workspace = sc_workspace.checkpoint().to_revertable();
 
-            let tx_result = self.runtime.dispatch_call(msg, &mut sc_workspace, &ctx);
+            let tx_result = self.runtime.dispatch_call(msg, sc_workspace, &ctx);
 
-            let events = sc_workspace.take_events();
+            // let events = sc_workspace.take_events();
```
Comment (ercecan) [inline crates/sovereign-sdk/module-system/sov-modules-stf-blueprint/src/stf_blueprint.rs]: why comment not delete

File: crates/sovereign-sdk/module-system/sov-modules-stf-blueprint/src/stf_blueprint.rs [hunk 4]
```diff
@@ -129,48 +128,39 @@ where
...
-                    TxEffect::Reverted
-                }
+                Err(e) => return Err(StateTransitionError::ModuleCallError(e)),
             };
             native_debug!("Tx {} effect: {:?}", hex::encode(raw_tx_hash), tx_effect);
 
             let receipt = TransactionReceipt {
                 tx_hash: raw_tx_hash,
-                events,
+                events: vec![],
```
Comment (ercecan) [inline crates/sovereign-sdk/module-system/sov-modules-stf-blueprint/src/stf_blueprint.rs]: maybe we can open an issue to remove events from receipt and other places (if there isn't one already)

File: crates/sovereign-sdk/module-system/sov-modules-stf-blueprint/src/stf_blueprint.rs [hunk 5]
```diff
@@ -129,48 +128,39 @@ where
...
 
                     tx_receipts.push(receipt);
-                    continue;
+
+                    return Err(StateTransitionError::HookError(e));
                 }
             };
             // Commit changes after pre_dispatch_tx_hook
-            sc_workspace = sc_workspace.checkpoint().to_revertable();
+            // sc_workspace = sc_workspace.checkpoint().to_revertable();
```
Comment (ercecan) [inline crates/sovereign-sdk/module-system/sov-modules-stf-blueprint/src/stf_blueprint.rs]: why is this not reverted in case of error now?

**Review by ercecan — DISMISSED** [review]
lgtm just one question and nits

File: crates/sovereign-sdk/module-system/sov-modules-stf-blueprint/src/stf_blueprint.rs (hunk 3 above)
Comment (eyusufatik) [reply crates/sovereign-sdk/module-system/sov-modules-stf-blueprint/src/stf_blueprint.rs]: I'll before finalizing the pr

File: crates/sovereign-sdk/module-system/sov-modules-stf-blueprint/src/stf_blueprint.rs (hunk 5 above)
Comment (eyusufatik) [reply crates/sovereign-sdk/module-system/sov-modules-stf-blueprint/src/stf_blueprint.rs]: we upstream error and expect whoever running this soft confirmation to discard any changes made by the soft confirmation until the error point

File: crates/evm/src/call.rs [hunk 6]
```diff
@@ -166,81 +162,46 @@ impl<C: sov_modules_api::Context> Evm<C> {
...
-                            block_number: block_number.saturating_to(),
-                        },
-                        receipt,
-                    };
+            let gas_used = result.gas_used();
+            cumulative_gas_used += gas_used;
+            let tx_hash = evm_tx_recovered.hash();
+            let tx_info = citrea_handler_ext
+                .get_tx_info(tx_hash)
+                .unwrap_or_else(|| panic!("evm: Could not get associated info for tx: {tx_hash}"));
```
Comment (rakanalh) [inline crates/evm/src/call.rs:176]:
```suggestion
                .expect("evm: Could not get associated info for tx: {tx_hash}");
```
But in general, i would rather this
```rust
.unwrap_or(anyhow!("evm: Could not get associated info for tx: {tx_hash}");
```
Since we are now returning errors.

File: crates/soft-confirmation-rule-enforcer/src/call.rs [hunk 7]
```diff
@@ -35,32 +39,31 @@ impl<C: Context, Da: DaSpec> SoftConfirmationRuleEnforcer<C, Da> {
...
         working_set: &mut WorkingSet<C>,
-    ) -> anyhow::Result<CallResponse> {
-        anyhow::ensure!(
-            *context.sender() == self.get_authority(working_set),
-            "Only authority can change the max L2 blocks per L1"
-        );
-
-        let mut data = self.data.get(working_set).expect("Data must be set");
+    ) -> Result<CallResponse, SoftConfirmationModuleCallError> {
+        if *context.sender() == self.get_authority(working_set) {
```
Comment (jfldde) [inline crates/soft-confirmation-rule-enforcer/src/call.rs]:
```suggestion
        if *context.sender() != self.get_authority(working_set) { return             Err(SoftConfirmationModuleCallError::RuleEnforcerUnauthorized) } 
```
And skip the else clause, makes it clearer imo

File: crates/evm/src/evm/tests.rs [hunk 8]
```diff
@@ -155,3 +158,14 @@ fn output(result: ExecutionResult) -> alloy_primitives::Bytes {
...
 }
+
+pub(crate) fn execute_tx<DB: Database + DatabaseCommit, EXT: CitreaExternalExt>(
+    db: DB,
+    block_env: BlockEnv,
+    tx: &TransactionSignedEcRecovered,
+    config_env: CfgEnvWithHandlerCfg,
+    ext: &mut EXT,
+) -> Result<ExecutionResult, EVMError<DB::Error>> {
+    let mut evm = CitreaEvm::new(db, block_env, config_env, ext);
```
Comment (rakanalh) [inline crates/evm/src/evm/tests.rs:168]: Not sure about the memory footprint of the EVM but isn't better if we instantiate once and invoke it everywhere we need to?

File: crates/evm/src/lib.rs [hunk 9]
```diff
@@ -125,20 +125,6 @@ pub struct Evm<C: sov_modules_api::Context> {
...
-    #[state]
-    pub(crate) native_pending_transactions:
-        sov_modules_api::AccessoryStateVec<PendingTransaction, BcsCodec>,
-
-    /// Transaction's hash that failed to pay the L1 fee.
-    /// Used to prevent DOS attacks.
-    /// The vector is cleared in `finalize_hook`.
-    #[cfg(feature = "native")]
-    #[state]
-    pub(crate) l1_fee_failed_txs: sov_modules_api::AccessoryStateVec<TxHash, BcsCodec>,
```
Comment (rakanalh) [inline crates/evm/src/lib.rs:140]: Idea: Should we invoke a migration to clear up storage related to these two removed items?

File: crates/evm/src/call.rs [hunk 10]
```diff
@@ -166,81 +162,46 @@ impl<C: sov_modules_api::Context> Evm<C> {
...
-                            cumulative_gas_used,
-                            logs,
-                        },
-                        gas_used: gas_used as u128,
-                        log_index_start,
-                        l1_diff_size: tx_info.l1_diff_size,
-                    };
-                    log_index_start += logs_len;
+            // take ownership of result.log() and use into()
+            let logs: Vec<_> = result.logs().iter().cloned().map(Into::into).collect();
```
Comment (jfldde) [inline crates/evm/src/call.rs]:
```
for (evm_tx_recovered, result) in users_txs.into_iter().zip(results.into_iter()) {
            // take ownership of result.log() and use into()

            let gas_used = result.gas_used();
            cumulative_gas_used += gas_used;
            let tx_hash = evm_tx_recovered.hash();
            let tx_info = citrea_handler_ext
                .get_tx_info(tx_hash)
                .unwrap_or_else(|| panic!("evm: Could not get associated info for tx: {tx_hash}"));

            let success = result.is_success();
            let logs = result.into_logs();
            let logs_len = logs.len() as u64;
            let receipt = Receipt {
                receipt: reth_primitives::Receipt {
                    tx_type: evm_tx_recovered.tx_type(),
                    success,
                    cumulative_gas_used,
                    logs,
                },
                gas_used: gas_used as u128,
                log_index_start,
                l1_diff_size: tx_info.l1_diff_size,
            };
            log_index_start += logs_len;

            let pending_transaction = PendingTransaction {
                transaction: TransactionSignedAndRecovered {
                    signer: evm_tx_recovered.signer(),
                    signed_transaction: evm_tx_recovered.into(),
                    block_number: block_number.saturating_to(),
                },
                receipt,
            };

            self.pending_transactions.push(pending_transaction);
        }
```
Can call result.into_logs() directly

File: crates/evm/src/evm/executor.rs [hunk 11]
```diff
@@ -99,8 +89,13 @@ pub(crate) fn execute_multiple_tx<
 
     let mut evm = CitreaEvm::new(db, block_env, config_env, ext);
 
-    let mut tx_results = Vec::with_capacity(txs.len());
+    let mut tx_results: Vec<ExecutionResult> = Vec::with_capacity(txs.len());
```
Comment (jfldde) [inline crates/evm/src/evm/executor.rs]:
```suggestion
    let mut tx_results = Vec::with_capacity(txs.len());
```
Can be inferred

File: crates/sovereign-sdk/rollup-interface/src/state_machine/soft_confirmation.rs [hunk 12]
```diff
@@ -109,9 +122,34 @@ impl<'txs, Tx: BorshSerialize> UnsignedSoftConfirmation<'txs, Tx> {
...
+            l1_fee_rate: self.l1_fee_rate,
+            timestamp: self.timestamp,
+        };
+
+        let raw = borsh::to_vec(&old).unwrap();
         D::digest(raw.as_slice())
     }
+
+    /// TODO: Documentation
+    pub fn get_old_format(&self) -> OldFormat<'txs> {
```
Comment (jfldde) [inline crates/sovereign-sdk/rollup-interface/src/state_machine/soft_confirmation.rs]:
```suggestion
    pub fn to_old_format(&self) -> OldFormat<'txs> {
```

File: crates/citrea-stf/src/hooks_impl.rs [hunk 13]
```diff
@@ -1,10 +1,11 @@
+use core::result::Result;
```
Comment (kpp) [inline crates/citrea-stf/src/hooks_impl.rs]: I don't think we need it. It's in core prelude

File: crates/evm/src/call.rs [hunk 14]
```diff
@@ -113,23 +112,20 @@ impl<C: sov_modules_api::Context> Evm<C> {
...
-            {
-                self.native_pending_transactions
-                    .push(&pending_transaction, &mut working_set.accessory_state());
-            }
 
             self.pending_transactions.push(pending_transaction);
         }
     }
 
+    // TODO: return module error here and in execute_*
```
Comment (kpp) [inline crates/evm/src/call.rs]: TODO?

File: crates/evm/src/call.rs (hunk 10 above)
Comment (kpp) [reply crates/evm/src/call.rs]: into_logs is actually better because it moves logs => we don't need extra allocs.

Comment (kpp) [reply crates/evm/src/call.rs]: Same must be done in `execute_system_events`

Comment (kpp) [reply crates/evm/src/call.rs:172]: Same must be done in `execute_system_events`

File: crates/evm/src/evm/executor.rs [hunk 15]
```diff
@@ -99,8 +89,13 @@ pub(crate) fn execute_multiple_tx<
...
     for (_i, tx) in txs.iter().enumerate() {
+        if tx.signer() == SYSTEM_SIGNER {
```
Comment (kpp) [inline crates/evm/src/evm/executor.rs]: Move this one after `let _span =` for a better debuggability

**Review by rakanalh — COMMENTED** [review]
Unfinished review. I'll continue in the morning.

File: crates/evm/src/lib.rs (hunk 9 above)
Comment (eyusufatik) [reply crates/evm/src/lib.rs:140]: hmm, we can, but they are small enough that we don't care.

File: crates/common/src/utils.rs [hunk 16]
```diff
@@ -77,3 +81,39 @@ pub fn check_l2_range_exists<DB: SharedLedgerOps>(
     }
     false
 }
+
+pub fn soft_confirmation_to_receipt<C: Context, Tx: TransactionDigest + Clone, DS: DaSpec>(
+    soft_confirmation: &SignedSoftConfirmation<'_, Tx>,
```
Comment (jfldde) [inline crates/common/src/utils.rs]: Could take ownership here

File: crates/common/src/utils.rs [hunk 17]
```diff
@@ -77,3 +81,39 @@ pub fn check_l2_range_exists<DB: SharedLedgerOps>(
...
+            let raw_tx_hash: [u8; 32] = digest.into();
+            tx_hashes.push(raw_tx_hash);
+        })
+    } else {
+        for raw_tx in soft_confirmation.blobs() {
+            let raw_tx_hash = <C as Spec>::Hasher::digest(raw_tx).into();
+
+            tx_hashes.push(raw_tx_hash);
+        }
+    };
```
Comment (jfldde) [inline crates/common/src/utils.rs]:
```suggestion
let tx_hashes = if current_spec >= SpecId::Fork1 {
        soft_confirmation
            .txs()
            .iter()
            .map(|tx| tx.compute_digest::<<C as Spec>::Hasher>().into())
            .collect()
    } else {
        soft_confirmation
            .blobs()
            .iter()
            .map(|raw_tx| <C as Spec>::Hasher::digest(raw_tx).into())
            .collect()
    };
```

File: crates/evm/src/evm/executor.rs (hunk 1 above)
Comment (eyusufatik) [reply crates/evm/src/evm/executor.rs]: then we'll figure something out :)

File: crates/sequencer/src/runner.rs (hunk 2 above)
Comment (eyusufatik) [reply crates/sequencer/src/runner.rs:341]: tbh I panicked bc for the sequencer, getting a hook error or soft confirmation error meant there is something fundamentally wrong with itself. if everybody says we shouldn't, then we can propagate error upstream

File: crates/sovereign-sdk/rollup-interface/src/state_machine/soft_confirmation.rs (hunk 12 above)
Comment (eyusufatik) [reply crates/sovereign-sdk/rollup-interface/src/state_machine/soft_confirmation.rs]: I was thinking smth like V1, what do you think?

File: crates/evm/src/call.rs (hunk 6 above)
Comment (eyusufatik) [reply crates/evm/src/call.rs:176]: so I used errors for things that would invalidate the soft confirmation e.g. a tx that doesn't work cannot be in a soft confirmation. 

however, in this example, we set tx info in the code before execution and then we get it after execution. if it doesn't happen, again it's a very very big problem; it will keep happening with correct soft. conf. as well. propagating the error doesn't help with anything

File: crates/evm/src/evm/tests.rs (hunk 8 above)
Comment (eyusufatik) [reply crates/evm/src/evm/tests.rs:168]: it's pretty light weight, since db is a set of accessors only, but I'll see what I can

File: crates/common/src/utils.rs [hunk 18]
```diff
@@ -77,3 +81,39 @@ pub fn check_l2_range_exists<DB: SharedLedgerOps>(
...
+        da_slot_height: soft_confirmation.da_slot_height(),
+        da_slot_hash: soft_confirmation.da_slot_hash().into(),
+        da_slot_txs_commitment: soft_confirmation.da_slot_txs_commitment().into(),
+        l1_fee_rate: soft_confirmation.l1_fee_rate(),
+        tx_hashes,
+        deposit_data: soft_confirmation.deposit_data().to_vec(),
+        timestamp: soft_confirmation.timestamp(),
+        soft_confirmation_signature: soft_confirmation.signature().to_vec(),
+        pub_key: soft_confirmation.pub_key().to_vec(),
+    }
```
Comment (yaziciahmet) [inline crates/common/src/utils.rs:119]: nit:
`fn into_receipt(self, tx_hashes)` can be implemented to soft confirmation to give the complete ownership and avoid cloning of any field.
even maybe `fn into_receipt(self, fork)`

File: crates/evm/src/evm/executor.rs [hunk 19]
```diff
@@ -111,34 +106,28 @@ pub(crate) fn execute_multiple_tx<
...
-                hex::encode(tx.hash())
-            )))
+            return Err(
+                SoftConfirmationModuleCallError::EvmGasUsedExceedsBlockGasLimit {
+                    cumulative_gas: cumulative_gas_used,
+                    tx_gas_used: result_and_state.result.gas_used(),
+                    block_gas_limit,
+                },
+            );
         } else {
```
Comment (yaziciahmet) [inline crates/evm/src/evm/executor.rs]: else statement can be removed here

File: crates/evm/src/genesis.rs [hunk 20]
```diff
@@ -1,7 +1,7 @@
+use core::result::Result;
```
Comment (yaziciahmet) [inline crates/evm/src/genesis.rs]: unnecessary

File: crates/sovereign-sdk/module-system/sov-modules-stf-blueprint/src/lib.rs [hunk 21]
```diff
@@ -506,44 +461,33 @@ where
...
-                            "Error applying soft confirmation: {:?} \n reverting batch workspace",
-                            err
-                        );
-                        Err(err)
-                    }
-                }
+                    &mut batch_workspace,
+                )?;
+
+                // TODO: can we pass workingset instead of checkpoint
```
Comment (yaziciahmet) [inline crates/sovereign-sdk/module-system/sov-modules-stf-blueprint/src/lib.rs]: TODO

**Review by yaziciahmet — DISMISSED** [review]

File: crates/sequencer/src/runner.rs (hunk 2 above)
Comment (yaziciahmet) [reply crates/sequencer/src/runner.rs:341]: I agree with panic here

**Comment by yaziciahmet** [comment]
One general suggestion I would make is that we use SoftConfirmationHookError everywhere, and to simplify it maybe we can create a type alias:

```rs
type SoftConfirmationHookResult<T> = Result<T, SoftConfirmationHookError>;
```

File: crates/sovereign-sdk/rollup-interface/src/state_machine/soft_confirmation.rs (hunk 12 above)
Comment (jfldde) [reply crates/sovereign-sdk/rollup-interface/src/state_machine/soft_confirmation.rs]: `to_v1_format` would be even better.
I was refering to https://rust-lang.github.io/api-guidelines/naming.html#ad-hoc-conversions-follow-as_-to_-into_-conventions-c-conv and following `to_*` convention.

File: crates/common/src/utils.rs (hunk 18 above)
Comment (eyusufatik) [reply crates/common/src/utils.rs:119]: gonna cause a circular dependency between rollup interface and sov-modules-core etc. 

I also want to show sov-tx-receipts are only used outside of stf

File: crates/sovereign-sdk/rollup-interface/src/state_machine/soft_confirmation.rs [hunk 22]
```diff
@@ -108,10 +123,27 @@ impl<'txs, Tx: BorshSerialize> UnsignedSoftConfirmation<'txs, Tx> {
...
+    pub fn to_v1_hash<D: Digest>(&self) -> Output<D> {
+        let old = self.to_v1();
+        let raw = borsh::to_vec(&old).unwrap();
         D::digest(raw.as_slice())
     }
+
+    /// Convert to old version of UnsignedSoftConfirmation
+    /// Used for backwards compatibility
+    /// Only applicable for pre-fork1
+    pub fn to_v1(&self) -> UnsignedSoftConfirmationV1<'txs> {
```
Comment (rakanalh) [inline crates/sovereign-sdk/rollup-interface/src/state_machine/soft_confirmation.rs]:
```rust
impl From<UnsignedSoftConfirmation> for UnsignedSoftConfirmationV1
```

**Review by rakanalh — COMMENTED** [review]
Noticed this while reviewing another PR. Please convert this to the idiomatic rust approach.

File: crates/sovereign-sdk/module-system/sov-modules-stf-blueprint/src/stf_blueprint.rs (hunk 4 above)
Comment (eyusufatik) [reply crates/sovereign-sdk/module-system/sov-modules-stf-blueprint/src/stf_blueprint.rs]: #1570

**Comment by eyusufatik** [comment]
> One general suggestion I would make is that we use SoftConfirmationHookError everywhere, and to simplify it maybe we can create a type alias:
> 
> ```rust
> type SoftConfirmationHookResult<T> = Result<T, SoftConfirmationHookError>;
> ```

I wont be doing this since this is done everywhere and it's going to mean a lot of imports and it does not shorten the code that much

**Review by kpp — APPROVED** [review]

File: crates/soft-confirmation-rule-enforcer/src/call.rs [hunk 23]
```diff
@@ -34,26 +38,25 @@ impl<C: Context, Da: DaSpec> SoftConfirmationRuleEnforcer<C, Da> {
...
-    ) -> anyhow::Result<CallResponse> {
-        anyhow::ensure!(
-            *context.sender() == self.get_authority(working_set),
-            "Only authority can change the authority"
-        );
-        self.authority.set(&address, working_set);
-        Ok(CallResponse::default())
+        working_set: &mut WorkingSet<C::Storage>,
+    ) -> Result<CallResponse, SoftConfirmationModuleCallError> {
+        if *context.sender() == self.get_authority(working_set) {
```
Comment (eyusufatik) [inline crates/soft-confirmation-rule-enforcer/src/call.rs]: use if not err

File: crates/sovereign-sdk/module-system/sov-modules-stf-blueprint/src/lib.rs [hunk 24]
```diff
@@ -483,70 +432,54 @@ where
...
+        StateTransitionError,
     > {
         let soft_confirmation_info = HookSoftConfirmationInfo::new(
             soft_confirmation,
             pre_state_root.as_ref().to_vec(),
             current_spec,
         );
 
-        match self.begin_soft_confirmation(
+        // TODO: maybe start checkpointing here
```
Comment (eyusufatik) [inline crates/sovereign-sdk/module-system/sov-modules-stf-blueprint/src/lib.rs]: remove todo

File: crates/sovereign-sdk/module-system/sov-modules-stf-blueprint/src/stf_blueprint.rs [hunk 25]
```diff
@@ -64,150 +58,84 @@ where
...
         let txs: Vec<_> = if soft_confirmation_info.current_spec >= SpecId::Fork1 {
-            txs_new
-                .iter()
-                .map(|tx| {
-                    let digest = tx.compute_digest::<<C as Spec>::Hasher>();
-                    let raw_tx_hash: [u8; 32] = digest.into();
-                    (raw_tx_hash, tx.clone())
-                })
-                .collect()
+            txs_new.to_vec()
```
Comment (eyusufatik) [inline crates/sovereign-sdk/module-system/sov-modules-stf-blueprint/src/stf_blueprint.rs:64]: this clone is probably avoidable create issue
