### PR TITLE
Telemetry fixes

### LINKED ISSUE #2101: Some metrics are not published as expected
## Summary

- Batch Prover
  - Current L1 block is not displaying any data
- Full Node
  - No metrics are submitted
- Sequencer
  - The following fields are not displaying data
    - Commit to L1
    - Commitment blocks count

### PR DESCRIPTION
**Pull request by rakanalh**
# Description

Testing happened on regtest

- Sequencer:
```
CITREA_VERBOSITY=1 ./target/debug/citrea --dev-all-forks --da-layer bitcoin --rollup-config-path resources/configs/bitcoin-regtest/sequencer_rollup_config.toml --sequencer resources/configs/bitcoin-regtest/sequencer_config.toml --genesis-paths resources/genesis/bitcoin-regtest/
```

- Full node
```
CITREA_VERBOSITY=1 ./target/debug/citrea --dev-all-forks --da-layer bitcoin --rollup-config-path resources/configs/bitcoin-regtest/rollup_config.toml --genesis-paths resources/genesis/bitcoin-regtest/
```

- Batch prover
```
PARALLEL_PROOF_LIMIT=1 ./target/debug/citrea --dev-all-forks --da-layer bitcoin --rollup-config-path resources/configs/bitcoin-regtest/batch_prover_rollup_config.toml --batch-prover resources/configs/bitcoin-regtest/batch_prover_config.toml --genesis-paths resources/genesis/bitcoin-regtest
```

## Sequencer

image

## Full node

image

## Batch prover

image

### CODE REVIEW

File: crates/risc0/src/host.rs [hunk 1]
```diff
@@ -154,7 +154,7 @@ impl ZkvmHost for Risc0BonsaiHost {
         let ProveInfo { receipt, stats } =
             prover.prove_with_opts(env, &elf, &ProverOpts::groth16())?;
 
-        histogram!("proving_session_cycle_count").record(stats.total_cycles as f64);
+        gauge!("proving_session_cycle_count").set(stats.total_cycles as f64);
```
Comment (eyusufatik) [inline crates/risc0/src/host.rs]: does gauge work for this?

Comment (rakanalh) [reply crates/risc0/src/host.rs]: Yes because we want to show the cycle count as-is and not the percentile. We can with gauage increment / decrement the value as received from the proving session which can be presented in a graph how it changes over time.

Comment (eyusufatik) [reply crates/risc0/src/host.rs]: cool. can you also update the dashboard yaml?

Comment (rakanalh) [reply crates/risc0/src/host.rs]: Never mind, restored this to a histogram but now we only show the real values and not quantiles since we need to visualize the actual values.

**Comment by Chinacolt** [comment]
Let's merge this to next release and test on dev-net.

**Review by Chinacolt — APPROVED** [review]
I don't have anything specific to comment.
Once this is merged to next release, we will test it on dev-net.

**Review by eyusufatik — APPROVED** [review]
