### PR TITLE
Fix EVM RPC's fee handling

### LINKED ISSUE #241: EVM: Add L1 fee to `eth_call` and other RPCs
RPCs that need updating:

- [x] eth_getBlockByHash and eth_getBlockByNumber (depends on #245)
- [x] eth_getTransactionReceipt
- [ ] debug_transaction (not quiet sure #244 probably introduced an implementation for this)

### LINKED ISSUE #247: EVM: decide on fees on `eth_call`
Currently, we:
- disable block gas fee
- disable base fee
- disable eip 3607
- don't track L1 fees

for eth_call and trace_transaction.

checked reth didn't see anything that disables base fees etc. for this. However it makes sense to do that too.

Will check geth and reth.

### PR DESCRIPTION
**Pull request by eyusufatik**
# Description
Read latest comments on issues

## Linked Issues
Closes #241 
Closes #247

### CODE REVIEW

**Review by otaliptus — CHANGES_REQUESTED** [review]

File: crates/evm/src/query.rs [hunk 1]
```diff
@@ -666,28 +682,38 @@ impl<C: sov_modules_api::Context> Evm<C> {
...
+                    .balance,
+            ),
+        )?;
 
         let from = request.from.unwrap_or_default();
         let to = if let Some(to) = request.to {
             to
         } else {
-            let account = evm_db.basic(from).unwrap_or_default();
+            let account = evm_db.basic(from).unwrap();
```
Comment (kpp) [inline crates/evm/src/query.rs:716]: What if `from` does not exist in the db yet?

File: crates/evm/src/query.rs [hunk 2]
```diff
@@ -666,28 +682,38 @@ impl<C: sov_modules_api::Context> Evm<C> {
...
 
             let nonce = account.unwrap_or_default().nonce;
```
Comment (kpp) [inline crates/evm/src/query.rs:718]: Okay, then we should check account.is_some here.

Comment (eyusufatik) [reply crates/evm/src/query.rs:718]: if account doesnt exists, the default impl. applies

**Review by kpp — APPROVED** [review]

**Review by otaliptus — APPROVED** [review]
