### PR TITLE
Crash recovery

### LINKED ISSUE #540: Risc0BonsaiHost crash recovery
If the prover crashes while waiting on Bonsai API, it shouldn't resubmit it's job, maybe leverage ledger db to start working from where it left off

### PR DESCRIPTION
**Pull request by ercecan**
# Description
WIP

## Linked Issues
- Fixes #540

### CODE REVIEW

**Comment by ercecan** [comment]
I tested the functionality manually, any Ideas on how to implement tests?

File: crates/sovereign-sdk/rollup-interface/src/state_machine/zk/mod.rs [hunk 1]
```diff
@@ -48,12 +48,26 @@ pub trait ZkvmHost: Zkvm + Clone {
...
     /// Extracts public input form the proof.
     fn extract_output<Da: DaSpec, Root: BorshDeserialize>(
         proof: &Proof,
     ) -> Result<StateTransition<Da, Root>, Self::Error>;
+
+    /// Waits for a receipt to be generated by the zkVM program.
+    fn wait_for_receipt(&self, session: &str) -> Result<Vec<u8>, anyhow::Error>;
+
+    /// Creates a new snark session in the zkVM program.
+    fn create_new_snark_session(&self, session: &str) -> Result<String, anyhow::Error>;
```
Comment (ercecan) [inline crates/sovereign-sdk/rollup-interface/src/state_machine/zk/mod.rs:62]: Just realized that this won't work in no-std because of String 
I will update it with a serialized version

Comment (ercecan) [reply crates/sovereign-sdk/rollup-interface/src/state_machine/zk/mod.rs]: Fixed

File: crates/sovereign-sdk/full-node/db/sov-db/src/ledger_db/traits.rs [hunk 2]
```diff
@@ -175,6 +175,28 @@ pub trait ProverLedgerOps: SharedLedgerOps {
...
     /// Set the witness by L2 height
     fn set_l2_witness<Witness: Serialize>(&self, l2_height: u64, witness: &Witness) -> Result<()>;
+
+    /// Returns the uuid of the bonsai session at l1 height, if not completed
+    /// Only returns a value if proof submission is not complete
+    fn get_bonsai_session_by_l1_height(&self, l1_height: u64) -> Result<Option<String>>;
+
+    /// Returns the uuid of the bonsai snark session at l1 height, if not completed
+    /// Only returns a value if proof submission is not complete
+    fn get_bonsai_snark_session_by_l1_height(&self, l1_height: u64) -> Result<Option<String>>;
```
Comment (eyusufatik) [inline crates/sovereign-sdk/full-node/db/sov-db/src/ledger_db/traits.rs:185]: plus create new trait called 

proving service ledger ops

**Review by eyusufatik — CHANGES_REQUESTED** [review]
we talked about what to change f2f

**Comment by ercecan** [comment]
> we talked about what to change f2f

done

File: crates/prover/src/runner.rs [hunk 3]
```diff
@@ -223,6 +223,29 @@ where
...
+            .recover_proving_sessions_and_send_to_da(&self.da_service)
+            .await?;
+        if results.is_empty() {
+            Ok(false)
+        } else {
+            for (tx_id, proof) in results {
+                self.extract_and_store_proof(tx_id, proof, l1_height)
+                    .await?;
+            }
+            self.ledger_db.clear_pending_proving_sessions()?;
```
Comment (eyusufatik) [inline crates/prover/src/runner.rs:244]: we might want to do this inside prover service if possible.

File: crates/prover/src/runner.rs [hunk 4]
```diff
@@ -467,83 +491,34 @@ where
...
-            // Skip submission until l1 height
-            if l1_height >= skip_submission_until_l1 && should_prove {
-                self.generate_and_submit_proof(transition_data, l1_height, hash)
+            let proving_session_exists = self
+                .check_and_recover_ongoing_proving_sessions(l1_height)
+                .await?;
+            if !proving_session_exists {
+                // There is no ongoing bonsai session to recover
+                let transition_data: StateTransitionData<Stf::StateRoot, Stf::Witness, Da::Spec> =
+                    self.create_state_transition_data(
```
Comment (eyusufatik) [inline crates/prover/src/runner.rs:504]: i don't think we should check this all the time, just on startup is fine, no?

File: crates/risc0-bonsai/src/host.rs [hunk 5]
```diff
@@ -11,10 +11,32 @@ use risc0_zkvm::{
...
+type StarkSession = String;
+type SnarkSession = String;
+
+/// Bonsai sessions to be recovered in case of a crash.
+#[derive(Debug, Clone, BorshSerialize, BorshDeserialize)]
+pub enum BonsaiSession {
+    /// Stark session id if the prover crashed during stark proof generation.
+    Session(StarkSession),
+    /// Both Stark and Snark session id if the prover crashed during stark to snarkconversion.
+    Snark(StarkSession, SnarkSession),
```
Comment (eyusufatik) [inline crates/risc0-bonsai/src/host.rs:28]: call it SnarkSession

**Review by eyusufatik — APPROVED** [review]
looking really good this time :)

just a few naming nits

File: crates/prover/src/runner.rs (hunk 3 above)
Comment (ercecan) [reply crates/prover/src/runner.rs:244]: done

File: crates/prover/src/runner.rs (hunk 4 above)
Comment (ercecan) [reply crates/prover/src/runner.rs:504]: done

File: crates/risc0-bonsai/src/host.rs (hunk 5 above)
Comment (ercecan) [reply crates/risc0-bonsai/src/host.rs]: Done

**Review by eyusufatik — APPROVED** [review]
