### PR TITLE
Fix duration underflow issue

### LINKED ISSUE #932: Sequencer substraction overflow
## Summary

Somehow block production took more than 2 seconds, and then, from my understanding the sequencer failed on these lines:

```rust
let mut interval = tokio::time::interval(target_block_time - parent_block_exec_time);
// The first ticket completes immediately.
// See: https://docs.rs/tokio/latest/tokio/time/struct.Interval.html#method.tick
interval.tick().await;
```

```sh
2024-07-30T14:45:00.251761Z ERROR Sequencer: panic: thread 'main' panicked at 'overflow when subtracting durations': /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/time.rs:1126
   0: <backtrace::capture::Backtrace as core::default::Default>::default
             at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/backtrace-0.3.73/src/capture.rs:422:9
   1: log_panics::Config::install_panic_hook::{{closure}}
             at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/log-panics-2.1.0/src/lib.rs:115:29
   2: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/alloc/src/boxed.rs:2034:9
      std::panicking::rust_panic_with_hook
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/panicking.rs:783:13
   3: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/panicking.rs:657:13
   4: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/sys_common/backtrace.rs:171:18
   5: rust_begin_unwind
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/panicking.rs:645:5
   6: core::panicking::panic_fmt
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/panicking.rs:72:14
   7: core::panicking::panic_display
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/panicking.rs:197:5
   8: core::panicking::panic_str
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/panicking.rs:172:5
      core::option::expect_failed
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/option.rs:1995:5
   9: core::option::Option<T>::expect
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/option.rs:896:21
      <core::time::Duration as core::ops::arith::Sub>::sub
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/time.rs:1126:31
  10: citrea_sequencer::sequencer::CitreaSequencer<C,Da,Sm,Vm,Stf>::run::{{closure}}::{{closure}}::{{closure}}
             at /root/citrea/crates/sequencer/src/sequencer.rs:856:54
  11: citrea_sequencer::sequencer::CitreaSequencer<C,Da,Sm,Vm,Stf>::run::{{closure}}::{{closure}}
             at /root/citrea/crates/sequencer/src/sequencer.rs:774:5
  12: citrea_sequencer::sequencer::CitreaSequencer<C,Da,Sm,Vm,Stf>::run::{{closure}}
             at /root/citrea/crates/sequencer/src/sequencer.rs:774:5
  13: citrea_sequencer::Sequencer<S>::run_and_report_rpc_port::{{closure}}
             at /root/citrea/crates/sequencer/src/lib.rs:57:19
  14: citrea_sequencer::Sequencer<S>::run::{{closure}}::{{closure}}::{{closure}}
             at /root/citrea/crates/sequencer/src/lib.rs:44:44
  15: citrea_sequencer::Sequencer<S>::run::{{closure}}::{{closure}}
             at /root/citrea/crates/sequencer/src/lib.rs:36:5
  16: <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll
             at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-0.1.40/src/instrument.rs:321:9
  17: citrea_sequencer::Sequencer<S>::run::{{closure}}
             at /root/citrea/crates/sequencer/src/lib.rs:36:5
  18: citrea::start_rollup::{{closure}}::{{closure}}::{{closure}}
             at /root/citrea/bin/citrea/src/main.rs:148:48
  19: citrea::start_rollup::{{closure}}::{{closure}}
             at /root/citrea/bin/citrea/src/main.rs:123:1
  20: citrea::start_rollup::{{closure}}
             at /root/citrea/bin/citrea/src/main.rs:123:1
  21: citrea::main::{{closure}}
             at /root/citrea/bin/citrea/src/main.rs:107:14
  22: tokio::runtime::park::CachedParkThread::block_on::{{closure}}
             at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.38.0/src/runtime/park.rs:281:63
  23: tokio::runtime::coop::with_budget
             at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.38.0/src/runtime/coop.rs:107:5
      tokio::runtime::coop::budget
             at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.38.0/src/runtime/coop.rs:73:5
      tokio::runtime::park::CachedParkThread::block_on
             at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.38.0/src/runtime/park.rs:281:31
  24: tokio::runtime::context::blocking::BlockingRegionGuard::block_on
             at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.38.0/src/runtime/context/blocking.rs:66:9
  25: tokio::runtime::scheduler::multi_thread::MultiThread::block_on::{{closure}}
             at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.38.0/src/runtime/scheduler/multi_thread/mod.rs:87:13
  26: tokio::runtime::context::runtime::enter_runtime
             at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.38.0/src/runtime/context/runtime.rs:65:16
  27: tokio::runtime::scheduler::multi_thread::MultiThread::block_on
             at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.38.0/src/runtime/scheduler/multi_thread/mod.rs:86:9
  28: tokio::runtime::runtime::Runtime::block_on
             at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.38.0/src/runtime/runtime.rs:349:45
  29: citrea::main
             at /root/citrea/bin/citrea/src/main.rs:93:5
  30: core::ops::function::FnOnce::call_once
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/ops/function.rs:250:5
  31: std::sys_common::backtrace::__rust_begin_short_backtrace
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/sys_common/backtrace.rs:155:18
  32: std::rt::lang_start::{{closure}}
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/rt.rs:166:18
  33: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/ops/function.rs:284:13
      std::panicking::try::do_call
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/panicking.rs:552:40
      std::panicking::try
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/panicking.rs:516:19
      std::panic::catch_unwind
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/panic.rs:146:14
      std::rt::lang_start_internal::{{closure}}
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/rt.rs:148:48
      std::panicking::try::do_call
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/panicking.rs:552:40
      std::panicking::try
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/panicking.rs:516:19
      std::panic::catch_unwind
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/panic.rs:146:14
      std::rt::lang_start_internal
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/rt.rs:148:20
  34: std::rt::lang_start
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/rt.rs:165:17
  35: main
  36: __libc_start_call_main
             at ./csu/../sysdeps/nptl/libc_start_call_main.h:58:16
  37: __libc_start_main_impl
             at ./csu/../csu/libc-start.c:360:3
  38: _start
  ```

### PR DESCRIPTION
**Pull request by rakanalh**
# Description
Some blocks might take more than 2 seconds to execute causing a panic when substracting durations.

## Linked Issues
- Fixes #932

### CODE REVIEW

**Comment by yaziciahmet** [comment]
Might be irrelevant to the PR, but imo we should use sleep instead of interval since on every loop we are creating a new instance. We can create a sleep instance and not await it, and use it in tokio::select statement

**Comment by rakanalh** [comment]
> Might be irrelevant to the PR, but imo we should use sleep instead of interval since on every loop we are creating a new instance. We can create a sleep instance and not await it, and use it in tokio::select statement

Interval is recommended over sleep to run things at regular intervals
https://docs.rs/tokio/1.17.0/tokio/time/fn.sleep.html

**Comment by yaziciahmet** [comment]
We run things at intervals, but we don't respect intervals. Proper usage of intervals would be, defining it outside of the for loop, and just putting interval.tick() into tokio::select statement. So for every 2 seconds for instance it would tick.

But we don't do this because we adjust the wait time based on prev exec time, and then just use it once for the first tick, and then re-create a new interval. This is the exact behavior of calling sleep every iteration.

File: crates/sequencer/src/sequencer.rs [hunk 1]
```diff
@@ -922,7 +922,14 @@ where
         let mut missed_da_blocks_count = 0;
 
         loop {
-            let mut interval = tokio::time::interval(target_block_time - parent_block_exec_time);
+            // We try to produce the next block based on how long the previous block took in terms
+            // of execution time. If last block takes more than target block time (2 secs),
+            // we just reset the interval to 2 secs.
+            let mut interval = if parent_block_exec_time > target_block_time {
+                tokio::time::interval(target_block_time)
```
Comment (eyusufatik) [inline crates/sequencer/src/sequencer.rs:929]: if producing the parent block took more than 2 secs, shouldn't we wait 0 seconds?

Comment (rakanalh) [reply crates/sequencer/src/sequencer.rs:929]: Each block gets created every 2 seconds.
If parent block takes 1.5 seconds, we produce the next block after 0.5 seconds but if the parent block takes it's whole slot we produce the next block after it's own 2 seconds.

Comment (rakanalh) [reply crates/sequencer/src/sequencer.rs:929]: Though the more correct approach to have consistent 2 second blocks would be:
If parent block takes 1.5 seconds, the remainder gets added to the next block's time to become 2.5 seconds.

File: crates/sequencer/src/sequencer.rs [hunk 2]
```diff
@@ -922,10 +922,15 @@ where
...
-            // See: https://docs.rs/tokio/latest/tokio/time/struct.Interval.html#method.tick
-            interval.tick().await;
+            let block_production_tick = tokio::time::sleep(
+                target_block_time
+                    .checked_sub(
+                        parent_block_exec_time
+                            .checked_sub(target_block_time)
+                            .unwrap_or_default(),
+                    )
+                    .unwrap_or_default(),
```
Comment (yaziciahmet) [inline crates/sequencer/src/sequencer.rs:932]: When parent_block_exec_time < target_block_time, we will always wait for 2 seconds (target_block_time), is that expected behavior?

**Review by yaziciahmet — COMMENTED** [review]
LGTM, got one question

File: crates/sequencer/src/sequencer.rs (hunk 2 above)
Comment (kpp) [reply crates/sequencer/src/sequencer.rs:932]: `target_block_time - (parent_block_exec_time - target_block_time)` ?

Comment (eyusufatik) [reply crates/sequencer/src/sequencer.rs:932]: > When parent_block_exec_time < target_block_time, we will always wait for 2 seconds (target_block_time), is that expected behavior?

yes

**Review by eyusufatik — APPROVED** [review]
