### PR TITLE
Fix sequencer not filling missed da blocks

### LINKED ISSUE #817: Sequencer failing to fill missing L1 blocks
## Summary
Running the sequencer locally I've noticed this:

```
2024-06-27T08:28:39.729687Z  INFO Sequencer: bitcoin_da::service: Getting block at height 409
2024-06-27T08:28:39.735620Z  WARN Sequencer: citrea_sequencer::sequencer: Sequencer is falling behind on L1 blocks by 3 blocks
2024-06-27T08:28:40.730330Z  INFO Sequencer: bitcoin_da::service: Getting block at height 406
2024-06-27T08:28:40.738167Z  INFO Sequencer: citrea_sequencer::sequencer: New block #138, DA #406, Tx count: #0
2024-06-27T08:28:40.738564Z  INFO Sequencer: bitcoin_da::service: Getting block at height 406
2024-06-27T08:28:40.743670Z  INFO Sequencer: citrea_sequencer::sequencer: New block #139, DA #406, Tx count: #0
2024-06-27T08:28:40.743992Z  INFO Sequencer: bitcoin_da::service: Getting block at height 406
2024-06-27T08:28:40.748462Z  INFO Sequencer: citrea_sequencer::sequencer: New block #140, DA #406, Tx count: #0
2024-06-27T08:28:40.748697Z ERROR Sequencer: citrea_sequencer::sequencer: Sequencer error: Sequencer: L1 height mismatch, expected 409 (or 409-1), got 406
2024-06-27T08:28:41.741036Z ERROR Sequencer: citrea_sequencer::sequencer: Sequencer error: Sequencer: L1 height mismatch, expected 409 (or 409-1), got 406
2024-06-27T08:28:41.742695Z  INFO Sequencer: bitcoin_da::service: Getting block at height 409
2024-06-27T08:28:41.748336Z  WARN Sequencer: citrea_sequencer::sequencer: Sequencer is falling behind on L1 blocks by 3 blocks
2024-06-27T08:28:42.743596Z  INFO Sequencer: bitcoin_da::service: Getting block at height 406
2024-06-27T08:28:42.752042Z  INFO Sequencer: citrea_sequencer::sequencer: New block #141, DA #406, Tx count: #0
2024-06-27T08:28:42.752590Z  INFO Sequencer: bitcoin_da::service: Getting block at height 406
2024-06-27T08:28:42.758769Z  INFO Sequencer: citrea_sequencer::sequencer: New block #142, DA #406, Tx count: #0
2024-06-27T08:28:42.759065Z  INFO Sequencer: bitcoin_da::service: Getting block at height 406
2024-06-27T08:28:42.763669Z  INFO Sequencer: citrea_sequencer::sequencer: New block #143, DA #406, Tx count: #0
2024-06-27T08:28:42.763829Z ERROR Sequencer: citrea_sequencer::sequencer: Sequencer error: Sequencer: L1 height mismatch, expected 409 (or 409-1), got 406
2024-06-27T08:28:43.754320Z  INFO Sequencer: bitcoin_da::service: Getting block at height 409
2024-06-27T08:28:43.756803Z ERROR Sequencer: citrea_sequencer::sequencer: Sequencer error: Sequencer: L1 height mismatch, expected 409 (or 409-1), got 406
2024-06-27T08:28:43.761208Z  WARN Sequencer: citrea_sequencer::sequencer: Sequencer is falling behind on L1 blocks by 3 blocks
2024-06-27T08:28:44.755271Z  INFO Sequencer: bitcoin_da::service: Getting block at height 406
2024-06-27T08:28:44.763580Z  INFO Sequencer: citrea_sequencer::sequencer: New block #144, DA #406, Tx count: #0
2024-06-27T08:28:44.763981Z  INFO Sequencer: bitcoin_da::service: Getting block at height 406
2024-06-27T08:28:44.768363Z  INFO Sequencer: citrea_sequencer::sequencer: New block #145, DA #406, Tx count: #0
2024-06-27T08:28:44.768645Z  INFO Sequencer: bitcoin_da::service: Getting block at height 406
2024-06-27T08:28:44.772625Z  INFO Sequencer: citrea_sequencer::sequencer: New block #146, DA #406, Tx count: #0
2024-06-27T08:28:44.772777Z ERROR Sequencer: citrea_sequencer::sequencer: Sequencer error: Sequencer: L1 height mismatch, expected 409 (or 409-1), got 406
2024-06-27T08:28:45.764960Z ERROR Sequencer: citrea_sequencer::sequencer: Sequencer error: Sequencer: L1 height mismatch, expected 409 (or 409-1), got 406
```

## Expected Result
The sequencer finds out there is more than one L1 block between its last used L1 block and the finalized DA height and creates a single L2 block for those "missing" L1 blocks.

## Actual Result
Sequencer is stuck in a loop.

### PR DESCRIPTION
**Pull request by yaziciahmet**
# Description
In the loop for filling in missed da blocks, da block counter was not incremented properly, causing sequencer to never fill missing blocks.

## Linked Issues
- Fixes #817 

## Testing
I reproduced #817 and observed that the blocks are catching up successfully.
Also added an e2e test.

### CODE REVIEW

**Review by eyusufatik — APPROVED** [review]

**Comment by eyusufatik** [comment]
are you going to write a test for this?

File: bin/citrea/tests/e2e/mod.rs [hunk 1]
```diff
@@ -3387,3 +3388,111 @@ async fn test_sequencer_commitment_threshold() {
...
+    // publish da blocks back to back
+    for _ in 0..to_be_filled_da_block_count {
+        da_service.publish_test_block().await.unwrap();
+    }
+    wait_for_l1_block(&da_service, latest_da_block, None).await;
+
+    let mut first_filler_l2_block = 1;
+    // wait for sequencer to notice the gap with the da
+    let mut retry_limit = 5;
+    loop {
```
Comment (rakanalh) [inline bin/citrea/tests/e2e/mod.rs:3440]: This loop should not be needed.

Once an L2 is published, the force handler and the regular handler should see that there are L1 blocks that were not filled. This will happen if you wait long enough which is 2 seconds by default. You can add a sleep on line 3436.

**Review by rakanalh — CHANGES_REQUESTED** [review]
Otherwise LGTM

File: crates/sequencer/src/sequencer.rs [hunk 2]
```diff
@@ -813,6 +813,7 @@ where
                             }
                         }
 
+                        // TODO: should not submit commitment if there are skipped blocks
```
Comment (rakanalh) [inline crates/sequencer/src/sequencer.rs:816]: 1. This calls `maybe_submit_commitment`
2. commitment_controller will return an error on missing L1 / L2 connection (btw, this logic is removed in #863 

This comment is not needed.

Comment (yaziciahmet) [reply crates/sequencer/src/sequencer.rs]: I though that it was a problem because of 2nd point, even though it functioned successfully. Removed https://github.com/chainwayxyz/citrea/pull/861/commits/e8cab68c5ff7b455a6213c074ad6243fa5e17e98

File: bin/citrea/tests/e2e/mod.rs (hunk 1 above)
Comment (yaziciahmet) [reply bin/citrea/tests/e2e/mod.rs:3440]: I am aware of that, but it feels flaky to me, as there is a possibility of changing the default L1 poll interval, which could cause this test to fail. Do you think it should be replaced with sleep despite that?

Comment (rakanalh) [reply bin/citrea/tests/e2e/mod.rs:3440]: Yes.... the sleep is configurable in `SequencerConfig` in the test so you can make the sleep you use more or equal to the duration of the sequencer L1 poll interval.

Comment (yaziciahmet) [reply bin/citrea/tests/e2e/mod.rs]: That is quite correct :). Here is the update: https://github.com/chainwayxyz/citrea/pull/861/commits/1b576570b7ae15c140cc78bd0d5fcc2d062888cc

**Review by rakanalh — APPROVED** [review]
LGTN
