### PR TITLE
fix: Readd deposit transactions

### LINKED ISSUE #2705: On block production error, all deposits are dropped
## Summary

If a block fails to be produced for any reason, we drop the deposits we drain from the deposit mempool. Instead, we can readd the deposits.

Cantina 159

### PR DESCRIPTION
**Pull request by rakanalh**
# Description

## Linked Issues
- Fixes #2705

### CODE REVIEW

File: crates/sequencer/src/deposit_data_mempool.rs [hunk 1]
```diff
@@ -42,30 +45,71 @@ impl DepositDataMempool {
...
+            .collect();
+
+        self.accepted_deposit_txs = remaining_deposits;
+
+        // Update metrics
+        SM.deposit_data_mempool_txs
+            .set(self.accepted_deposit_txs.len() as f64);
+
+        debug!("Removed {} deposits from mempool", removed_count);
+        removed_count
```
Comment (eyusufatik) [inline crates/sequencer/src/deposit_data_mempool.rs:106]: since this is a queue, only the count is enough to remove the deposits from the mempool. so you don't need to the following:

```rust
self
    .accepted_deposit_txs
    .drain(..)
    .filter(|deposit| {
        if let Ok(txid) = Self::calc_tx_id(deposit) {
            if txids_to_remove.contains(txid.as_slice()) {
                // Remove from pending set
                self.pending_deposits.remove(txid.as_slice());
                removed_count += 1;
                return false;
            }
        }
        true
    })
    .collect();
```

but just `.drain(..deposits.len())`

Comment (eyusufatik) [reply crates/sequencer/src/deposit_data_mempool.rs:106]: but you still have to remove form txid set that's correct

**Review by eyusufatik — CHANGES_REQUESTED** [review]

File: crates/sequencer/src/deposit_data_mempool.rs (hunk 1 above)
Comment (rakanalh) [reply crates/sequencer/src/deposit_data_mempool.rs:106]: An even better approach would be to call `retain` let me update accordingly

Comment (eyusufatik) [reply crates/sequencer/src/deposit_data_mempool.rs:106]: keeping the retain approach as it's a safer API

**Review by eyusufatik — APPROVED** [review]

**Review by kpp — APPROVED** [review]

File: crates/sequencer/src/deposit_data_mempool.rs [hunk 2]
```diff
@@ -42,30 +45,65 @@ impl DepositDataMempool {
...
             if let Ok(txid) = Self::calc_tx_id(deposit) {
-                self.pending_deposits.remove(txid.as_slice());
+                txids_to_remove.insert(txid.to_vec());
             }
         }
 
-        deposits
+        // Retain only deposits that are not in the removal set
+        self.accepted_deposit_txs.retain(|deposit| {
+            if let Ok(txid) = Self::calc_tx_id(deposit) {
```
Comment (jfldde) [inline crates/sequencer/src/deposit_data_mempool.rs]: Shouldn't we return the error here as that would only happen in a corrupted state ? Above as well

**Review by jfldde — APPROVED** [review]

File: crates/sequencer/src/deposit_data_mempool.rs (hunk 2 above)
Comment (eyusufatik) [reply crates/sequencer/src/deposit_data_mempool.rs]: yeah, good point.

@rakanalh we can panic on calc_tx_id errors in this function. it should never be called with non-deposit Vec

Comment (rakanalh) [reply crates/sequencer/src/deposit_data_mempool.rs]: I checked. `calc_tx_id` doesn't really return an error... it always returns `Ok`. We should change the signature of the method.
