### PR TITLE
fix: subscription server unordered log delivery

### LINKED ISSUE #3155: Log subscription via websocket may return logs in random order
## Summary
Currently the websocket server implementation will spawn a new task for each websocket message sending process, since these tasks are executed randomly by the runtime, sometimes the order of the logs received by subscribers are not the same as they are in the blocks, which is against Ethereum spec `logIndex` semantics

In order to mitigate this we should open up a new task for each subscriber as they subscribe and pass it a broadcast stream, inside the task the subscribers will keep receiving the data from stream and instead of sending the data in a separate task, they will now send them sequentially to preserve `logIndex` ordering.

### PR DESCRIPTION
**Pull request by ercecan**
# Description
Because the messages are sent concurrently, this was the main reason behind flaky #3153  

## Linked Issues
- Fixes #3155 #3153

### CODE REVIEW

File: crates/ethereum-rpc/src/subscription.rs [hunk 1]
```diff
@@ -37,150 +27,138 @@ impl SubscriptionManager {
         ledger_db: LedgerDB,
         l2_block_rx: broadcast::Receiver<u64>,
     ) -> Self {
-        let (new_heads_tx, new_heads_rx) = mpsc::channel(16);
-        let (logs_tx, logs_rx) = mpsc::channel(16);
-
-        let head_subscriptions = Arc::new(RwLock::new(vec![]));
-        let logs_subscriptions = Arc::new(RwLock::new(vec![]));
+        let (heads_tx, _) = broadcast::channel(16);
+        let (logs_tx, _) = broadcast::channel(16);
```
Comment (jfldde) [inline crates/ethereum-rpc/src/subscription.rs]: Should bump that to higher values

File: crates/ethereum-rpc/src/subscription.rs [hunk 2]
```diff
@@ -37,150 +27,138 @@ impl SubscriptionManager {
...
                 }
             }
         }
-        // Drop lock to release the read lock.
-        drop(subscriptions);
     }
 }
 
-pub async fn l2_block_event_handler<C: sov_modules_api::Context>(
+async fn l2_block_event_handler<C: sov_modules_api::Context>(
```
Comment (eyusufatik) [inline crates/ethereum-rpc/src/subscription.rs:150]: if we put a shutdown handler here, subscription tasks auto close. but need to drop txs

**Review by eyusufatik — CHANGES_REQUESTED** [review]
add changelog pls

File: crates/ethereum-rpc/src/subscription.rs (hunk 2 above)
Comment (ercecan) [reply crates/ethereum-rpc/src/subscription.rs:150]: When SubscriptionManager is dropped, heads_tx and logs_tx are dropped with it. This causes every subscriber task's rx.recv() to return RecvError::Closed on the next iteration, and the task exits. So the tasks are self-terminating.

**Review by jfldde — APPROVED** [review]

**Review by eyusufatik — APPROVED** [review]
