### PR TITLE
fix: Notify subscribers about missing L2 blocks

### LINKED ISSUE #2758: send websocket notifications on missed da blocks
## Summary
cantina 227

### PR DESCRIPTION
**Pull request by kpp**
Fixes https://github.com/chainwayxyz/citrea/issues/2758

### CODE REVIEW

**Review by rakanalh — COMMENTED** [review]
Sorry, i don't get how this notifies about missing L2 blocks.

**Review by rakanalh — APPROVED** [review]

File: crates/sequencer/src/runner.rs [hunk 1]
```diff
@@ -436,7 +434,17 @@ where
...
+        match result {
+            Ok(l2_height) => {
+                // Only errors when there are no receivers
+                let _ = self.l2_block_tx.send(l2_height);
+            }
+            Err(e) => {
+                error!("Sequencer error: {}", e);
+            }
+        }
+
```
Comment (eyusufatik) [inline crates/sequencer/src/runner.rs]: should we have the `l2_block_tx.send()` before the metrics are saved maybe? @ercecan

Comment (ercecan) [reply crates/sequencer/src/runner.rs]: I guess it makes sense, maybe we can also separately time the duration of sending process just in case, and add it to the very top of the stacked block production graph in our grafana dashboard

Comment (eyusufatik) [reply crates/sequencer/src/runner.rs]: let's include the sending, but seperate tracking is overkill

Comment (kpp) [reply crates/sequencer/src/runner.rs]: Done

**Review by ercecan — APPROVED** [review]

**Review by eyusufatik — APPROVED** [review]
