### PR TITLE
Pass L1 fee rate through Context and modify Stf ( and its blueprint)

### LINKED ISSUE #1049: Store l1 fee rate in block env
they are always accessed together. to reduce cycle counts, storing l1_fee_rate inside block env makes sense

### LINKED ISSUE #1051: Bypass state read/writes by extending Context
e.g. pass L1 fee rate by context so that we don't save it to state in evm hooks

### LINKED ISSUE #1057: Sequencer skips block N1 (0 and 2 are covered)
## Summary

```
2024-08-29T10:47:59.739279Z  INFO citrea_sequencer::sequencer: Starting RPC server at 127.0.0.1:44737 
2024-08-29T10:47:59.740219Z  INFO Sequencer: bitcoin_da::service: Block not found, waiting
2024-08-29T10:48:09.801577Z  INFO Sequencer: citrea_sequencer::sequencer: New block #0, DA #121, Tx count: #0
2024-08-29T10:48:09.819362Z  INFO Sequencer: citrea_sequencer::sequencer: New block #2, DA #121, Tx count: #0
2024-08-29T10:48:09.836296Z  INFO Sequencer: citrea_sequencer::sequencer: New block #3, DA #121, Tx count: #0
```

## Steps to reproduce

1. SKIP_GUEST_BUILD=0 RUST_BACKTRACE=0 make test basic_prover_test -- --nocapture

## Expected Result

blocks 0, 1, 2...

## Actual Result

blocks 0, 2, 3...

### PR DESCRIPTION
**Pull request by eyusufatik**
# Description
We used to write L1 fee rate to state and read from it in EVM's sov-call function. Now we pass it through the context which is passed to dispatch of sov-calls. Everywhere else can access the L1 fee rate throught HooksSoftConfirmatinInfo.

While working on the PR I realized we made some mistakes on the typings of hooks and functions of the StfBluePrint so I also fixed that. 

## Linked Issues
- Closes #1049 
- Closes #1051 
- Closes #1057

## Testing
Will fix test compilation errors

### CODE REVIEW

File: crates/sovereign-sdk/module-system/sov-modules-stf-blueprint/src/stf_blueprint.rs [hunk 1]
```diff
@@ -238,42 +232,12 @@ where
...
     // Single malformed transaction results in sequencer slashing.
-    fn verify_txs_stateless_soft(&self, txs: &[Vec<u8>]) -> Vec<TransactionAndRawHash<C>> {
+    fn verify_txs_stateless_soft(&self, txs: Vec<Vec<u8>>) -> Vec<TransactionAndRawHash<C>> {
         verify_txs_stateless(
-            txs.iter()
-                .map(|tx| RawTx { data: tx.clone() })
+            txs.into_iter()
+                .map(|tx| RawTx { data: tx })
                 .collect::<Vec<_>>(),
         )
```
Comment (kpp) [inline crates/sovereign-sdk/module-system/sov-modules-stf-blueprint/src/stf_blueprint.rs:242]: Maybe get rid of Vec<Vec<>> and .collect()

File: crates/sequencer/src/sequencer.rs [hunk 2]
```diff
@@ -481,6 +474,7 @@ where
 
                 let (soft_confirmation_receipt, checkpoint) = self.stf.end_soft_confirmation(
                     active_fork_spec,
+                    self.state_root.clone().as_ref().to_vec(),
```
Comment (kpp) [inline crates/sequencer/src/sequencer.rs:477]:
```suggestion
                    self.state_root.to_vec(),
```

This should work because state_root is &[u8]?

File: crates/evm/src/tests/queries/mod.rs [hunk 3]
```diff
@@ -368,12 +410,13 @@ pub fn init_evm_with_caller_contract() -> (Evm<C>, WorkingSet<C>, TestSigner) {
         .unwrap();
     }
 
-    evm.end_soft_confirmation_hook(&mut working_set);
+    evm.end_soft_confirmation_hook(&soft_confirmation_info, &mut working_set);
```
Comment (kpp) [inline crates/evm/src/tests/queries/mod.rs:413]: Can we pass `soft_confirmation_info` instead of `&soft_confirmation_info` to end_ functions?

File: crates/sovereign-sdk/module-system/sov-modules-stf-blueprint/src/stf_blueprint.rs [hunk 4]
```diff
@@ -2,16 +2,14 @@ use std::marker::PhantomData;
...
-use sov_rollup_interface::spec::SpecId;
+use sov_rollup_interface::soft_confirmation::SignedSoftConfirmation;
 use sov_rollup_interface::stf::{
     SoftConfirmationError, SoftConfirmationReceipt, TransactionReceipt,
 };
-use sov_state::Storage;
-#[cfg(all(target_os = "zkvm", feature = "bench"))]
-use sov_zk_cycle_macros::cycle_tracker;
+// #[cfg(all(target_os = "zkvm", feature = "bench"))]
+// use sov_zk_cycle_macros::cycle_tracker;
```
Comment (kpp) [inline crates/sovereign-sdk/module-system/sov-modules-stf-blueprint/src/stf_blueprint.rs:12]: Why not?

**Review by kpp — APPROVED** [review]

File: crates/evm/src/tests/queries/mod.rs (hunk 3 above)
Comment (eyusufatik) [reply crates/evm/src/tests/queries/mod.rs:413]: yeah i guess it works

File: crates/sovereign-sdk/module-system/sov-modules-stf-blueprint/src/stf_blueprint.rs (hunk 1 above)
Comment (eyusufatik) [reply crates/sovereign-sdk/module-system/sov-modules-stf-blueprint/src/stf_blueprint.rs:245]: i don't understan

File: crates/sovereign-sdk/module-system/sov-modules-stf-blueprint/src/stf_blueprint.rs (hunk 4 above)
Comment (eyusufatik) [reply crates/sovereign-sdk/module-system/sov-modules-stf-blueprint/src/stf_blueprint.rs:12]: wasn't used anymore since I removed a function

**Comment by eyusufatik** [comment]
https://github.com/chainwayxyz/citrea/issues/1051#issuecomment-2317994938

File: crates/evm/src/tests/queries/mod.rs (hunk 3 above)
Comment (eyusufatik) [reply crates/evm/src/tests/queries/mod.rs:413]: to runtime functions we can, to module functions we can unfortunately

**Review by ercecan — APPROVED** [review]

**Review by rakanalh — APPROVED** [review]
LGTM

**Comment by rakanalh** [comment]
To resolve RPC tests:
```
TRYBUILD=overwrite cargo test rpc_tests
```

**Comment by eyusufatik** [comment]
> To resolve RPC tests:
> 
> ```
> TRYBUILD=overwrite cargo test rpc_tests
> ```

no I really broke them this time :D

fixing one by one

File: crates/sovereign-sdk/module-system/sov-modules-stf-blueprint/src/stf_blueprint.rs [hunk 5]
```diff
@@ -64,23 +66,27 @@ where
         txs: Vec<Vec<u8>>,
         mut sc_workspace: WorkingSet<C>,
     ) -> (WorkingSet<C>, Vec<TransactionReceipt<TxEffect>>) {
-        let txs = self.verify_txs_stateless_soft(txs);
+        let mut tx_receipts = Vec::with_capacity(txs.len());
+        for raw_tx in txs {
+            let raw_tx_hash = <C as Spec>::Hasher::digest(&raw_tx).into();
+            // Stateless verification of transaction, such as signature check
+            // Single malformed transaction results in sequencer slashing.
```
Comment (eyusufatik) [inline crates/sovereign-sdk/module-system/sov-modules-stf-blueprint/src/stf_blueprint.rs:73]: remove this comment, no slashing on us

File: crates/sovereign-sdk/module-system/sov-modules-stf-blueprint/src/stf_blueprint.rs [hunk 6]
```diff
@@ -64,23 +66,27 @@ where
...
+                .expect("Sequencer must not include non-deserializable transaction.");
+            tx.verify()
+                .expect("Sequencer must include correctly signed transaction.");
+            // Checks that runtime message can be decoded from transaction.
+            // If a single message cannot be decoded, sequencer is slashed
+            let msg = match RT::decode_call(tx.runtime_msg()) {
+                Ok(msg) => msg,
+                Err(e) => {
+                    native_error!("Tx 0x{} decoding error: {}", hex::encode(raw_tx_hash), e);
+                    panic!("Decoding transactions from the sequencer failed");
```
Comment (eyusufatik) [inline crates/sovereign-sdk/module-system/sov-modules-stf-blueprint/src/stf_blueprint.rs:84]: let's not panic here

File: crates/sovereign-sdk/module-system/sov-modules-stf-blueprint/src/stf_blueprint.rs [hunk 7]
```diff
@@ -64,23 +66,27 @@ where
         txs: Vec<Vec<u8>>,
         mut sc_workspace: WorkingSet<C>,
     ) -> (WorkingSet<C>, Vec<TransactionReceipt<TxEffect>>) {
-        let txs = self.verify_txs_stateless_soft(txs);
+        let mut tx_receipts = Vec::with_capacity(txs.len());
+        for raw_tx in txs {
+            let raw_tx_hash = <C as Spec>::Hasher::digest(&raw_tx).into();
```
Comment (eyusufatik) [inline crates/sovereign-sdk/module-system/sov-modules-stf-blueprint/src/stf_blueprint.rs:71]: we are using raw_tx_hash only for logging, let's do it only there then.

File: crates/sovereign-sdk/module-system/sov-modules-core/src/module/spec.rs [hunk 8]
```diff
@@ -101,14 +102,26 @@ pub trait Context: Spec + Clone + Debug + PartialEq + 'static {
...
-    fn new(sender: Self::Address, sequencer: Self::Address, height: u64) -> Self;
+    fn new(
+        sender: Self::Address,
+        sequencer: Self::Address,
+        height: u64,
+        active_spec: SpecId,
+        l1_fee_rate: u128,
+    ) -> Self;
+
+    /// TODO: remove
```
[the remark this answers is not in the document]
Comment (eyusufatik) [reply crates/sovereign-sdk/module-system/sov-modules-core/src/module/spec.rs:114]: removing that will be a later task. changes a lot of things 🤷

**Comment by eyusufatik** [comment]
> To resolve RPC tests:
> 
> ```
> TRYBUILD=overwrite cargo test rpc_tests
> ```

ok. in the end, I really needed it because I added a line to a file and all the numbers in the expected output was shifted by one
