### PR TITLE
fix: Decrement ongoing proving job count on error

### LINKED ISSUE #2824: decrement job count on `ParallelProverService::start_proving` err paths

### PR DESCRIPTION
**Pull request by ercecan**
# Description
The ongoing_proving_jobs is incremented in reserve_proof_slot after that this is the only path it can error out?

## Linked Issues
- Fixes #2824

### CODE REVIEW

**Review by eyusufatik — APPROVED** [review]
Aproving, but please spend some time thinking on different paths this can happen, or even other metrics this could happen

**Review by jfldde — APPROVED** [review]

File: crates/prover-services/src/parallel.rs [hunk 1]
```diff
@@ -179,18 +180,20 @@ where
...
+            proof_was_in_queue = true;
             warn!("Reached parallel proof limit, waiting for one of the proving tasks to finish");
         }
 
         let permit = self.proof_semaphore.clone().acquire_owned().await?;
 
         PARALLEL_PROVER_METRICS.ongoing_proving_jobs.increment(1);
 
-        if available_permits == 0 {
+        if proof_was_in_queue {
```
Comment (ercecan) [inline crates/prover-services/src/parallel.rs]: Same thing but easier to understand at first glance
